### PR TITLE
Add unit tests for version.py

### PR DESCRIPTION
**Pull request by St4rz**
Add unit tests for version.py to test the version.

Also includes formatting fix for test_align.py, a formatting fix for
an import statement in setup.py, and ignoring the .vscode directory
for developers that use VSCode.

See also: #476

### Testing
Run pytest in the project root.

### CODE REVIEW

**Comment by St4rz** [comment]
cc: @willingc 

I didn't add any reviewers upon creating this PR. Could you review it or assign it to someone, please?

**Comment by St4rz** [comment]
@tsibley MockVersion is just doing everything that version.py does, plus a little extra. Thinking back I don't like the approach. It's not DRY, and version.py probably doesn't even need to be unit tested.
I'll keep your commit policy in mind.

I'm thinking about pulling these changes out and just rejecting the PR. What are your thoughts?

**Comment by tsibley** [comment]
@St4rz Nod, I agree.

I think the unit tests here are falling into the trap of the test and mocks being a re-implemention of the thing they are "testing", as well as adding lines of code and re-factorings (like `def _get_version`) that aren't particularly useful.

I do think an "integration test" of some variety for `augur version` would make sense. For example, running both `augur version` and `augur --version` and checking that the text sent to stdout matches the expected version (or maybe just something that looks like _a_ version).

**Comment by St4rz** [comment]
Yes, that makes sense too. I open a different PR then. Thanks @tsibley!

**Pull request closed without merging**
