### PR TITLE
JSON schema 2.0 proposal

### PR DESCRIPTION
**Pull request by jameshadfield**
As we roll out modular augur, this is the correct time to make breaking changes to the current JSON schema. Here is my proposal for the meta & tree JSONs (easiest to just read the schemas themselves: https://github.com/nextstrain/augur/blob/new-schema/augur/data/schema_tree.json & https://github.com/nextstrain/augur/blob/new-schema/augur/data/schema_meta.json). Please comment / add commits to this PR.

**note: this schema is not yet supposed to be run by `augur validate` as it will fail**

### Main changes
* Make it clearer which values live on a tree node itself, and which in `node.attr` (or `node.traits` as I’ve called it).
	*  The “traits” store inferred data which is build-specific, as opposed to the properties on the node which should be present in most builds.
	* Confidence / entropy are stored together with the value itself. We have 2 types of confidence - `[x, y]` and `{valA: 0.4, valB: 0.3, …}`, maybe these should get different keys to distinguish them?
* Everything’s camelCase
* Keys have been renamed to make it clearer what they relate to
* The color-bys specifications have been made clearer and more powerful (continuing from https://github.com/nextstrain/auspice/issues/571)
* Vaccine information is now a property of the node, not in meta. I’m not sure what structure this should take.
* `node.muts` and `node.aa_muts` are combined into `node.mutations` paralleling the structure of `metadataJSON.annotations`
* The string version of a node date is gone and we just use `numDate` for everything
* Missing values (i.e. unknown accession) are excluded from the JSON rather than getting a `?` or `null` value. Schema validation can enforce this.
* Encode a JSON schema version in the metadata JSON

### Should we combine the tree & meta JSONs
I.e. a single JSON, with `json.tree`  referring to the nested node structure. There is probably a reason why y’all went with the two JSONs originally?

Any other breaking changes we can think of should be added to this PR.

### CODE REVIEW

**Comment by trvrb** [comment]
Thoughts in no particular order:

* snake_case vs camelCase: I definitely prefer snakecase. This is mainly because this felt more natural to cast attributes down to. Traits will fit better as: `north_dakota`, `new_zealand` than `northDakota`, `newZealand`. This is what I've been using for all the [lat/long](https://github.com/nextstrain/augur/blob/master/augur/data/lat_longs.tsv) and [color](https://github.com/nextstrain/augur/blob/master/augur/data/colors.tsv) lookups. I believe more natural for most people to cast their data into. Also fits with current use of `flu_seasonal_h3n2_ha_3y`. If we look at existing JSON APIs, snake_case is quite common: https://stackoverflow.com/a/25368854/9631919.

* I imagine that everything in `traits` should show up in the tip modal as metadata.

* Ambivalent about `muts`/`aa_muts` vs `mutations`.

* I like enforcing missing values to be excluded.

* I like `labels` for clade labels.

* What is the purpose of `hidden`?

* It seems a bit verbose to have `node.traits.country.value`, but I think this is the best we can do to make `node.traits.country.confidence` make sense.

* I'm very happy saying that `confidence` for a number should be of the form `[x, y]` and `confidence` for a string be `{valA: 0.4, valB: 0.3, …}`. I can't think of a situation where this wouldn't be the case.

* I think we may be able to better generalize `vaccine`. This is just getting used as a tip "label" / "annotation". Can be generic, like microcephaly cases for Zika for example. Or fatal cases. I'm very happy decommissioning vaccine selection date, vaccine deployment date, etc... Wasn't so useful.

* Change `href` to `url` in `maintainers`.

* Change `href` to `url` in `author_info`.

* An ordinal color scale is possible by just ordering the domain values in the appropriate order. Maybe this should be augur export's job?

**Comment by jameshadfield** [comment]
Thanks @trvrb!

> snake_case vs camelCase...
Whichever you prefer. Auspice uses camelCase exclusively in the code, so i'll just change the names there when the JSON is parsed. That's along the line of the link you provided: "Python » JSON » JavaScript - snake_case will make sense; screw the front-end anyways"

> what is the point of `hidden`?
This will be used by auspice to not display nodes, thus allowing exploded trees or multiple trees to be displayed at the same time by creating a polytomic root that is not displayed.

> An ordinal color scale is possible by just ordering the domain values in the appropriate order.
I envisaged a discrete scale useing a continuous colour scale where values next to each other would be close in colourspace ([example](http://colorbrewer2.org/#type=diverging&scheme=PiYG&n=6)), whereas an ordinal scale would use unrelated colours ([example](http://colorbrewer2.org/#type=qualitative&scheme=Set2&n=6))


Everything else seems fine by me - i'll let you deal with the vaccine stuff.

**Comment by trvrb** [comment]
"Hidden" makes sense. 

I would normally do ordinal data "A", "B", "C", "D" with a color ramp where "A" and "B" are closer in colorspace than "A" and "C" to match the semantics of an ordinal variable (where "A" and "B" are closer in value than "A" and "C").

**Comment by jameshadfield** [comment]
Ahhh yes you're right. I was trying to specify nominal / qualitative scales when I was saying "ordinal". How about "continuous", "ordinal", "nominal" scales.

**Comment by trvrb** [comment]
I like "continuous", "ordinal" and "categorical". "nominal" is also just fine. To me, less familiar. There would only be a difference between "ordinal" and "categorical" if `color_map` (or `hex_map`) is not defined, in which case default ordinal map would be the rainbow and categorical would be more like the genotype colors on nextflu.

**Comment by rneher** [comment]
just a few thoughts of my jet-lagged brain:
 * why not unify nuc/aa mutations completely and add a `type` field that species which is which?
 * latitudes vary between -90 and 90

**Comment by jameshadfield** [comment]
I've updated the schemas (see commits) and also proposed to unify the meta & tree JSONs.
I'll let trevor handle the vaccines and richard handle the mutations.

**Comment by jameshadfield** [comment]
Thanks @rneher - i've removed the `sys.exit` calls and instead returned `1` from the module, as this is what all other modules currently do. I would be in favor of modules raising an exception on errors which is handled in `bin/augur`, however that's outside this PR.

@emmahodcroft This PR now produces both nextflu-like (Tree & meta) and new (Unified) JSONs - see the snakefiles in the tests. I've done this by creating a second `auspice_config.json`, but please convert this to command line args to `augur export` 👍 

I've modified the nextflu-like schemas so they pass with TB - please modify the new schema so that the v2 schemas pass.

**Comment by emmahodcroft** [comment]
- I made a few small changes, all of which are already in v1 (whitespace, 'N' in nuc muts, accession, gene names)
- I changed the TB meta.tsv to work with expected journal title format

But I've got two types of error remaining: 

- Nucleotide mutations seem to be being compared to the pattern intended for AA muts (line [334](https://github.com/nextstrain/augur/blob/8ada425966f3dcad7f6e9b070ee6ea6adcf96a89/augur/data/schema.json#L334)) rather than the patterns immediately preceding for nuc muts. 

- I'm getting author lookup key errors because it wants a publication year, which I don't have in my meta file - just author and paper title. How flexible or inflexible do we want to be on this? I think being able to have a minimal amount of author into can be useful, but adding in journal etc could be a pain. IMO this is a lookup key and so we should be flexible.

**Comment by emmahodcroft** [comment]
@jameshadfield I started working on modifications to `export` to do away with the `config.json`, but haven't quite finished - I'll update tomorrow!

**Comment by jameshadfield** [comment]
> Nucleotide mutations seem to be being compared to the pattern intended for AA muts (line 334) rather than the patterns immediately preceding for nuc muts.

Ok. Will fix after your work on removing the config JSON

> I'm getting author lookup key errors because it wants a publication year, which I don't have in my meta file - just author and paper title. How flexible or inflexible do we want to be on this? I think being able to have a minimal amount of author into can be useful, but adding in journal etc could be a pain. IMO this is a lookup key and so we should be flexible.

The code is supposed to be flexible and not crash if there's no year in the publication -- it should just create a key without it. This is the aim anyways.

**Comment by emmahodcroft** [comment]
> The code is supposed to be flexible and not crash if there's no year in the publication (or no publication, or no title... but maybe an author is essential). It should just create a key with the data that's available. This is the aim anyways.

In that case maybe it could be a warning in `validate` instead of an error (is that possible?), since it will presumably display fine in `auspice`. 

WRT config-free-`export`, I've added these new params/arguments, but they could probably do with some discussion. All except `title` can take lists:
- `title`
- `maintainers` 
- `maintainers-urls` - should be same order as above
- `geography-traits` - location trait names to use on the map (ex: country, region)
- `extra-traits` - metadata columns not run through `traits` to be mapped onto tree
- `panels` - what panels to display; default is "tree, map, entropy"

`traits` (from running `traits`) are taken from what's on the nodes (read in from the `node-data` files) and these along with `extra-traits` are automatically included in colouring and filtering

I've definitely made a few assumptions that should be checked, and haven't fully tested with all types of missing data. And, of course, I can't look at the final outcome in `auspice` (this only works for v2 schema)! It validates with the same 2 remaining errors (above) that I get from v1 export. 

(Will push soon)

**Comment by tsibley** [comment]
I don't think `nextflu-schema` is a good name for the current/soon-to-be-old schema version.  How about we call it version 1 and the new schema version 2?

The schemas should enforce that the JSON files declare their schema version as a constant. Using `$version` is conventional, e.g.:

```json
{
    "$version": 1,
    "title": "Real-time tracking of Zika virus evolution",
    …
}
```

**Comment by emmahodcroft** [comment]
Sorry, didn't check with zika yet. Works for TB. Hopefully gives an idea of how it might work, and I'll look at zika.

**Comment by jameshadfield** [comment]
> The schemas should enforce that the JSON files declare their schema version as a constant. Using $version is conventional

Yup, that's fine, and the new / 2.0 schema has a field like this, but the old / nextflu-like / tree+meta / 1.0 JSONs didn't have this field, so it can't be enforced. 

> I don't think nextflu-schema is a good name for the current/soon-to-be-old schema version. How about we call it version 1 and the new schema version 2?

I'm ambivalent -- i'm hoping that it won't be around for too long!

**Comment by trvrb** [comment]
Can't version be enforced for 2.0 schema even if not enforced for 1.0 schema? I do think that nextflu-schema is too cryptic.

**Comment by tsibley** [comment]
> Yup, that's fine, and the new / 2.0 schema has a field like this, but the old / nextflu-like / tree+meta / 1.0 JSONs didn't have this field, so it can't be enforced.

The version 1 / old version can be recognized by the _lack_ of a `$version` declaration in that case.

The version 2 / new version schema doesn't quite have what I mean.  The `version` field it defines is:

```json
        "version" : {
            "description": "JSON schema version",
            "type" : "string",
            "pattern": "^[0-9]+[.][0-9]+$"
        },
```

but this allows any arbitrary number, thus not trying a particular `schema.json` to the document to be validated.  What I'm suggesting is something like:

```json
        "$version" : {
            "description": "Nextstrain schema version",
            "type" : "string",
            "enum" : ["2"]
        },
```

and then we'd rename `augur/data/schema.json` to `augur/data/schema-v2.json`.

When we need to change the schema in the future, we can make a copy and bump the version number to 3, and so forth.  Does that make sense?  (I don't know whether we only need/want integer versions, or if we should start with [semantic versioning](https://semver.org), e.g. 2.0.0).

> I'm ambivalent -- i'm hoping that it won't be around for too long!

I'm less concerned about how long it'll be around and more concerned that we leave ourselves a clear path forward for schema changes in the future.

**Comment by tsibley** [comment]
One benefit of what I'm proposing for versions is that it provides a means of introspection for augur/auspice when they're ingesting a data file.  They can look at the `$version` field (or note it's lack) and then know what to expect from the rest of the data file.  This might mean loading the appropriate `data/schema-v*.json` file to validate or running the correct set of chained data migrations to best-effort upgrade an older data file into a new schema.

**Comment by jameshadfield** [comment]
Sounds great @tsibley -- please add commits effecting these changes.

**Comment by tsibley** [comment]
Ok. I won't have time until next week, but I will add it then. I don't feel the need to do the work myself if you'd like to do it sooner.

Also, there's a lot to look at on this branch, and this is the first thing that jumped out at me so I thought I'd start the conversation about it.  I will be digging into the schemas more, but again, realistically not until next week.  I'm excited that we're headed down this path!

**Comment by trvrb** [comment]
I really like explicit versions like `schema-v2.json`. How does this work with `augur export`. Is there a `--schema-version 2` flag that is current default that we then increment alongside schema versions?

**Comment by tsibley** [comment]
> How does this work with augur export. Is there a --schema-version 2 flag that is current default that we then increment alongside schema versions?

Yep, that sounds reasonable to me.

**Comment by tsibley** [comment]
Well, actually, there are parts of `augur export --schema-version` that aren't as reasonable.  We don't want to have to maintain `augur export`'s ability to export multiple schema versions indefinitely.  I think `augur export` should always emit the latest schema version.  If you need an old schema version, then use an appropriately old version of augur.

There is some wiggle room here if we want to maintain two or three recent versions for some overlapping period of time to ease transitions, but I don't think we should commit to indefinitely.

**Comment by trvrb** [comment]
So in this case, perhaps `augur export defaults to ` --schema-version latest`? And at some point `augur export` loses the ability to call `--schema-version 1`?

**Comment by jameshadfield** [comment]
Yes. That's why I called it `nextflu-like`, as that's the only long term reason to maintain exporting a 1.0 schema.

**Comment by tsibley** [comment]
I think that defaulting to `--schema-version 2` is fine, where "2" gets bumped with each new schema version.  That is, I don't think we need a special `latest` keyword/alias.  My point was mostly that we explicitly don't want to support arbitrary schema versions indefinitely.  This means that for now `--schema-version 1` and `--schema-version 2` will work, but eventually the former stops being supported. And the same with `--schema-version 2` once we have a version 3, etc.

**Comment by emmahodcroft** [comment]
exportv2 now works for Zika and validates sucessfully

**Comment by jameshadfield** [comment]
Thanks all - after discussion with @trvrb this is now going into `master`. There's plenty of points raised in this thread and it's felt each is best served by it's own issue / PR. I encourage everyone to go ahead and make these so that the schema changes now and not (so much) in the future.

**Pull request merged**
