### PR TITLE
Add exception catch for empty titers files.

### PR DESCRIPTION
**Pull request by barneypotter24**
This PR addresses https://github.com/nextstrain/augur/issues/279. It adds a try/except clause before the tree model is trained in `augur titers` that replaces the expected `potency` and `avidity` outputs with empty dictionary. This prevents builds from crashing if they fail to find any titers, as is the case with NIID 2y HI H3N2 builds.

I have tested this with both the above titer-less build that was previously failing and with a similar build that was working before this change, both ran without error.

### CODE REVIEW

**Comment by barneypotter24** [comment]
Thank you for these suggestions @huddlej! Let's sit down early next week to fix this more robustly.

**Comment by barneypotter24** [comment]
@huddlej I've added the changes that we worked through yesterday.

**Comment by trvrb** [comment]
Sorry to be late commenting here. Thank you for the detailed review @huddlej. My thoughts for ideal behavior are a bit different. I would say:

* if the `titers.tsv` input file is missing then, yes, throw an exception and write message to standard error
* if the `titers.tsv` input file exists but has 0 titers or only a handful such that running the tree model or the subs model produces an "empty" model with no branches/subs of antigenic impact, then throw a warning but still write out JSON

Here, I'm thinking mainly towards our own use case of running `seasonal-flu` on a matrix of builds some of which are missing titer data. Pushing this logic into the snakemake file will be overly complex. Have to maintain a list of builds missing titer data in snakemake and also alter downstream behavior (so that `auspice_config` specifies colors differently). This is all neatly solved by writing out an minimal JSON from `augur titers`).

>Along those lines, we could add an option to the titers command to allow empty models such that the command still writes out a valid JSON when there isn’t enough data. 

This is also a good solution in my view. We'd use this `--allow-empty-model` flag in `seasonal-flu`, but then the default behavior targets the cleaner scenario.

**Comment by huddlej** [comment]
@trvrb I agree; I would not want to handle the conditional logic in Snakemake either. I think Barney's most recent implementation addresses both of our concerns.

The Python module now responds to missing data in a way that can be handled programmatically (an exception instead of a warning sent to standard error). The command line interface catches the missing data exception and exits with an error message and non-zero exit code, but it also provides users with an option to override the missing data exception if they choose.

**Comment by barneypotter24** [comment]
Thanks all for your comments here. As @huddlej described the new behavior is to have the models threw an exception if they find insufficient data, and to have the CLI handle that exception either by exiting, or by writing an empty model (if the `--allow-empty-model` flag is provided). 

This will let us add the flag to seasonal flu builds so that the builds mentioned in https://github.com/nextstrain/augur/issues/279 can complete normally, while in most other cases that don't have sufficient data will cause the CLI to fail.

**Comment by trvrb** [comment]
@huddlej @barneypotter24: I see. This behavior sounds great to me.

**Pull request merged**
