### PR TITLE
Update release process

### PR DESCRIPTION
**Pull request by victorlin**
### Description of proposed changes

Some changes prompted by the release of 15.0.2 – a first using [the GitHub Actions workflow](https://github.com/nextstrain/augur/actions/workflows/release.yaml), which had some unexpected bumps.

### Related issue(s)

_N/A_

### Testing

Unable to test until next release.

### Pre-merge

- [ ] rebase commits

### Post-merge

- [ ] delete `release` branch

### CODE REVIEW

**Review by huddlej — CHANGES_REQUESTED** [review]
This will make life a bit easier for us! As part of this PR, could you also remove references to the "release" branch from [the DEV_DOCS](https://github.com/nextstrain/augur/blob/master/docs/contribute/DEV_DOCS.md) and add a link to how to manually rebuild the Docker image (https://github.com/nextstrain/docker-base#rebuilding-an-image-and-pushing-to-docker-hub)?

**Review by huddlej — APPROVED** [review]
Looks good to me! I'm sure we can refine more on the next release. :)

**Comment by victorlin** [comment]
Oops, I meant to rebase commits before merging, but no biggie.

**Comment by tsibley** [comment]
The removal of the `release` branch [broke the build](https://github.com/nextstrain/docker-base/runs/6560060218?check_suite_focus=true#step:5:2936) of the Docker runtime image, which used the `release` branch to [install the latest stable version of Augur](https://github.com/nextstrain/docker-base/blob/3360407528a4c460ade96ceee42cddcb92a5f488/Dockerfile#L85-L86). I'll fix that up, though there's a larger discussion to be had about if it makes any sense any more for Augur and Auspice to be installed from Git instead of PyPI/NPM.

**Pull request merged**
