### PR TITLE
Allow boolean metadata values. Closes #299

### LINKED ISSUE #299: Export V2: True & False Metadata Doesn't Work
I haven't tested this in V1, but since we've gotten this far and are about to push to V2, I suggest maybe not to worry about it.

If a column in metadata consists only of values 'True'/'False'/'true'/'false', `pandas.read_csv` automatically parses this to boolean values.
(`utils.py` `read_metadata`)

Later, in `export.py` `transfer_metadata_to_strains`, we transfer traits by asking:
` if trait in raw_data and raw_data[trait]: `
If the _value_ of that trait is `False` then the value for that trait will not be transferred... So this just disappears. Then all values are `True`. This unexpectedly results in a Legend will all values of '1':
image

But I can debug this further once we decide on a fix for this initial problem.

It would be good if there's an option in `pandas.read_csv` that prevents this conversion somehow...? So that we can 'manually' convert this to 'our kind of boolean' later? If not, I'm unsure how to handle. Ideas?

### PR DESCRIPTION
**Pull request by jameshadfield**
Includes a test build with three boolean metadata traits: `1/0`, `True/False`, `Yes/No`.

Note that auspice needs to be updated to at least https://github.com/nextstrain/auspice/commit/6de5a7d0ca77c6fbdf8949c3735eaf95f9a86ca3 for this to work (v2 branch)

image

### CODE REVIEW

**Comment by emmahodcroft** [comment]
Overall looking good! However, if some data have missing values, it reverts back to categorical:
image

image
(Also slightly unsure why the unknown are showing up yellow rather than grey - but this may be because of mismatch between augur and auspice version for colouring or something...)

This seems to happen with true/false, 0/1, and yes/no.

**Comment by emmahodcroft** [comment]
This also affects missing data in traits that should be guessed as 'continuous'. (Ex: my 'age' data in the EV-D68 build.)
This must have crept in with another change, as I definitely tested this when I added that guessing bit. Problem is same in both - value of `''` mess up the `all` test in both cases. 

Along the same vein, may want to think about how `NA`, `N/A`, and `unknown` values are treated here. My vote would be to ignore missing data in all forms (including `''`) and guess from the remaining.

**Comment by jameshadfield** [comment]
> why the unknown are showing up yellow rather than grey

This is because the trait has been guessed as "categorical" and there are 3 values -- `True`, `False`, `''`

Bigger question: Auspice has a function `isValueValid` which ignores the values in `[undefined, "undefined", "unknown", "?", "nan", "na", "n/a"];` (it should also include empty strings - todo!). But augur doesn't do this. It seems not ideal to ignore these fields for guessing, but export them anyway. How do you feel about detecting missing values & not exporting them?

**Comment by emmahodcroft** [comment]
> But augur doesn't do this. It seems not ideal to ignore these fields for guessing, but export them anyway. How do you feel about detecting "missing" values & not exporting them? (By "missing" I mean to use the same criteria as auspice.)

Yes, I think this is a good solution! Might also want to include 'not known' (I see this one a lot, for some reason).

**Comment by jameshadfield** [comment]
do not know why this is "closed" and do not think I did it 🤔

**Comment by emmahodcroft** [comment]
I'm afraid Github says you did! 😆  
image

But yes I was wondering why you had closed it myself... Certainly I do not think it's closed, so I'd vote to re-open.

**Comment by jameshadfield** [comment]
Yeah turns out I "closed" it as this PR was to merge `true-false-traits` into -v6-divOnly`. When the latter was merged into `v6` then this PR decided its time was up & closed itself.

Anyways it's now been merged into `v6` 🎉

**Comment by emmahodcroft** [comment]
Sorry, have now become behind enough it's hard for me to catch up 🙃 Did we implement the above 'detect missing data', or put it as an issue somewhere to implement? Or does this still need to be done?

**Comment by jameshadfield** [comment]
I did it, I think... can you check with your dataset?!?

**Comment by emmahodcroft** [comment]
OK! On a train ATM, will try to check ASAP :)

**Comment by emmahodcroft** [comment]
Yes - seems to work now for missing data when using 'true/false' and 'yes/no'. For using 0 and 1, this seems always to be guessed as continuous (with our without missing data - so that's good!). 

This seems to be because the `0` and `1` values are read in as doubles (`0.0`, `1.0`), then in the test on line 138 in export_v2.py, they are converted to strings (`'0.0'`, `'1.0'`), but compared to a string list that only contains `'0'` and `'1'`! Including `'0.0'` and `'1.0'` in the test list seems to fix this!

**Comment by emmahodcroft** [comment]
Also there's this: 
image

And this:
image
(for all branches, even those that definitely have True/False info on them)

I'm using the `v2` branch of `auspice`, so ignore if this is rectified in something not-yet-merged.

**Comment by jameshadfield** [comment]
Good find. I think this is going to have to be tackled in https://github.com/nextstrain/auspice/issues/760 (more work 🤦‍♂ 🤦‍♀ )

**Comment by emmahodcroft** [comment]
Ok, I'll push a commit adding `'0.0'` and `'1.0'` to the test list in `export v2`, (as doesn't seem to have been done yet) and we can address the tip-label thing in `auspice` as you say!

**Pull request closed without merging**
