### PR TITLE
Dengue gets #fancy (major code cleanup + docs, added auspice options, and improved titer model exports)

### PR DESCRIPTION
**Pull request by sidneymbell**
This PR implements a handful of new features for the dengue build:

Visualization:
* Country-level colorby and georesolution; still no country-level geo-inference (unreliable with so many demes / low N per deme)  
* Display cTiter for the all-dengue build. Display dTiter from the sanofi vaccine strain for serotype-specific builds.

Titers:  
* Adapt the code needed to generate Neher et al. Figure 4, which sanity checks the assumptions that titers are symmetrical and show tree-like evolution.  
* Save the `actual` and `predicted` titer values from the test dataset to csv for downstream analyses.  
  
General:  
* Fairly major code cleanup + reorganization  
* Added extensive comments   
* Already includes branch `default-colors` (PR #68)  
  
Will push the new JSONs up to the dev server momentarily. Comments, feedback, ideas and issues welcome. Otherwise, will plan to merge in a couple of days.

### CODE REVIEW

**Comment by trvrb** [comment]
Thanks @sidneymbell. Going through this now.

**Comment by trvrb** [comment]
The first two commits 2200ea383182c6c9bcddf7f479afd477cfaa7711 and 937b0979913ab6aaa23625939147c8e59bceee24 to change default colors have now been merged into `master`.

**Comment by sidneymbell** [comment]
@trvrb @jameshadfield - The new JSONs are up on the dev server; take a look when you have a minute? If no objections, I'll plan to push these live this afternoon.

**Comment by jameshadfield** [comment]
@sidneymbell looks good to me. 
FYI you mean _staging_ server, not _dev_ server ;)

I'll make 2 issues for little bugs that are more general problems with auspice rather than dengue (I think) - the first box in the cTiter color ramp has no value, and the header when filtering to authors has `?` in the names...

**Comment by trvrb** [comment]
Nice work @sidneymbell. I wasn't able to do a detailed code review, but the walking through the changes looks like this makes things easier to understand. I was also able to run the build without problems on my end. A couple small suggestions:

1. I think it would be good to get all the builds into the same canonical `regions`. Dengue is currently the outlier here because sequences in fauna date from before I went back to the now canonical regions:

China, Southeast Asia, South Asia, Japan Korea, Oceania, West Asia, Africa, Europe, South America, North America

There is not a hurry here, but I think it would be nice to update dengue in fauna to follow these regions (should happen naturally with the geo synonyms that now exist) and then match colors to what I did for flu:

https://github.com/nextstrain/augur/blob/master/builds/flu/colors.flu.tsv

This ramp makes it so that nearby regions have similar colors (more so than current dengue ramp).

2. The "antigenic distance to vaccine" colorby should probably have branches colored. We have a good infnerence for what these branches are according to the titer model.

dengue-vaccine

These antigenic breakpoints are interesting.

3. I also worry that these numbers aren't very interpretable without the vaccine "X" on the tree (like we have in Nextflu). What about reporting antigenic distance from root of each serotype? Would still give an idea of how much variation exists within a serotype.

**Comment by trvrb** [comment]
To be more clear here, I wouldn't consider any of these 3 blocking. Item 2 seems like the biggest issue and the easiest to fix.

**Comment by sidneymbell** [comment]
Thanks for your thoughts, guys! This is really helpful.  

@jameshadfield - Yes, I think the first box missing a label is an auspice bug. I think the authors filter is a dengue issue. I'll look into it and/or add a filter.  
  
@trvrb - Ah, these are all great thoughts, thanks.  
1 - With the exception of a handful of strains, these have now been updated to reflect whatever is currently in the fauna `source` data (I built this into the `--update_locations` functionality the last time the regions were redefined). This should get reflected in the next rebuild.  
  
2 - Absolutely. I figured out `scipy.optimize.minimize` yesterday for the titer model regularization parameters, and need to rerun anyways. It's a one-line fix to also assign the `dTiter_sanofi` attribute to nodes.  
  
3 - I totally agree it's hard to interpret without seeing the reference strain. However, I think this is equally true whether the mystery-reference is a strain of interest or the root (I personally find thinking about antigenic distance from "the root" really abstract/difficult to interpret).   
  
In the short term, I'm in favor of leaving it for now: it's got some context issues either way, but this at least provides a concrete piece of interesting information? Thoughts?  
  
In the medium term, I think it'd be pretty easy to make the sanofi tip/circle larger when `dTiter_sanofi` colorby is selected. I'm already pulling that reference tip in augur (can assign an extra `attr`), and the action to make specific tip/circles larger already exists in auspice, just needs to be fired.  
   
In the long term, it'd be great to implement the old nextflu functionality for selecting reference strains.

**Comment by sidneymbell** [comment]
(Please don't delete this branch, I continue to use it as a sandbox for non-nextstrain dengue model development)

**Comment by trvrb** [comment]
Progress looks good.

>(Please don't delete this branch, I continue to use it as a sandbox for non-nextstrain dengue model development)

The best way to do this is to make a new branch off of `master` after you've merged a PR. Call it `dengue-dev-2` or whatever. Or even better `dengue-titers` or whatever you're mainly working on in the branch.

**Pull request merged**
