### PR TITLE
Export versioning

### PR DESCRIPTION
**Pull request by joverlee521**
This commit addresses issue #297 and contains two other PRs #277 and #300. 

`augur export` has been split into `augur export default` and `augur export v1`. This allows us to preserve all v1 export code in a separate file that will not need to be updated. We removed all references to v1 in the default export file. 

**_NOTE_**: `augur export` will need to be updated in all builds (see updated test builds)

### CODE REVIEW

**Comment by tsibley** [comment]
Just saw this PR description and thought I'd chime in on one point. I would encourage the commands to be `augur export v1` and `augur export v2` and explicitly not support something like `augur export default` or `augur export latest`. The reason is that if builds always have to explicitly pick a version, they won't break when the default/latest changes and can update to the new version on their own terms/timeline.

**Comment by jameshadfield** [comment]
Thanks @joverlee521 -- i'll take a look at this today/tomorrow 👍 

Given that this is a breaking change to the `augur export` interface I think we merge this into a `v2-json` branch, and subsequently merge future schema modifications / augur export tweaks expected over the next 2-3 weeks.

**Comment by trvrb** [comment]
I'd like to not break existing builds if possible. I don't quite see why we can't just have 'augur export --schema v1' and 'augur export --schema v2' and have this default to 'augur export --schema v2'. If augur is upgraded, an existing build would go to producing v2 JSONs but 'auspice view' should transparently work with this.

**Comment by jameshadfield** [comment]
@trvrb @tsibley i'm gonna move the args conversation to a new issue as I told @joverlee521 & @kairstenfay to not worry too much about this for this PR as we'll have a separate pass through all the args later.

**Comment by jameshadfield** [comment]
Thanks @joverlee521 @kairstenfay this looks great 🎉 

I've rebased this onto master & merged into a `v6` branch, where we'll continue modifying `augur export` and related code before a major version release.

**Pull request closed without merging**
