### PR TITLE
Upgrade treetime to v0.7

### PR DESCRIPTION
**Pull request by rneher**
creating this PR not for immediate merging but for discussion and testing. 

TreeTime underwent a number of changes from 0.6 to 0.7. Among other things
  * you can't mess with `node.sequence` anymore as these are now protected
  * tip states are not reconstructed by default anymore
  * traits inference is followed by numerical optimization of the overall switching rate. This doesn't require the 'short branch length' assumption that was made previously and that is violated for rapidly changing states. 
 * numerical date conversion is now handled more consistently

Our traits code messes with `node.sequences`, so this needed changing. Other than that, I have not noticed any problems but it will be good to check more thoroughly, also test treetime.

### CODE REVIEW

**Comment by rneher** [comment]
Validation is failing, however, since augur is now exporting mutations like `A564W` which are not valid nucleotide mutations according to the schema. We need to decide how we want to report those. Some data sets like Ebola also contain other illegal characters like `?` in sequences. those would now show up as 

image

**Comment by rneher** [comment]
This should implement the issues we discussed last night. The Ebola ancestral reconstruction now looks proper in auspice:
image

Augur now goes through TTs map of characters to likelihood profiles and identifies fully ambiguous characters which are all mapped to 'N'

**Comment by rneher** [comment]
With the updated v1 schema, this passes tests now. Should be ready to merge and address #429

**Comment by rjabhinav** [comment]
augur ancestral: error: ambiguous option: --output could match --output-node-data, --output-sequences, --output-vcf    trying to run the zika tutorial please help

**Comment by emmahodcroft** [comment]
Hi @rjabhinav, it's best to open a new issue if you need help. Please don't reply to this PR anymore, but open an issue if you need further help. 

We apologise that the instructions for the Zika tutorial have gone out of date somewhat. `augur ancestral` now has two output options that must be specified: `--output-node-data` and `--output-sequences`. Please try setting both of these and see if this works. If not, please open a new issue!

**Pull request merged**
