### PR TITLE
filter: Reorganize Cram test files

### PR DESCRIPTION
**Pull request by victorlin**
### Context

The current filter.t is pretty cumbersome to work with (see [Slack thread](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1653072787820709)).

### Description of proposed changes

This change breaks that file into several smaller files.

- Split filter.t into much smaller files:
    - For most files, each is setup + one augur filter command.
    - A few files also check the output or run related commands.
- Re-organize supporting files so that everything is under tests/functional/filter/, which has two folders:
    - cram: individual test files
    - data: supporting data (previously directly under tests/functional/filter/)

Some noticeable differences:

- Easy to have a high-level overview of tests:

    ```
    % ls -1 tests/functional/filter/cram/
    _setup.sh
    filter-exclude-include.t
    filter-metadata-duplicates-error.t
    filter-metadata-not-found-error.t
    filter-metadata-sequence-strains-mismatch.t
    ...
    ```

- Progress dots and numbers on test results are more meaningful:

    ```
    % cram --shell=/bin/bash tests/functional/filter/cram/
    ........................
    # Ran 24 tests, 0 skipped, 0 failed.
    ```

- Easy to run just one test:

    ```
    % cram --shell=/bin/bash tests/functional/filter/cram/filter-no-outputs-error.t 
    .
    # Ran 1 tests, 0 skipped, 0 failed.
    ```

- There is more setup overhead for each test, but in terms of run time it's only a 1 second difference:

    ```
    % time cram --shell=/bin/bash tests/functional/filter.t    
    .
    # Ran 1 tests, 0 skipped, 0 failed.
    cram --shell=/bin/bash tests/functional/filter.t  30.09s user 5.89s system 135% cpu 26.567 total
    ```

    vs.

    ```
    % time cram --shell=/bin/bash tests/functional/filter/cram/
    ........................
    # Ran 24 tests, 0 skipped, 0 failed.
    cram --shell=/bin/bash tests/functional/filter/cram/  30.28s user 6.16s system 132% cpu 27.598 total
    ```

### Related issue(s)

_N/A_

### Testing

See CI.

### CODE REVIEW

**Review by huddlej — COMMENTED** [review]
Cool! I like the new layout and test filenames. We'll need to update both [the CI test runner](https://github.com/victorlin/augur/blob/5fdd864786b808ccb43687ce352f42db257a01f8/.github/workflows/ci.yaml#L46) and [the `run_test.sh` script](https://github.com/victorlin/augur/blob/5fdd864786b808ccb43687ce352f42db257a01f8/run_tests.sh#L25) to search for Cram tests in a smarter way. Actually, I just noticed (thanks to your example code) that Cram has its own smart search built in so this works:

```
cram --shell=/bin/bash tests/
```

**Comment by victorlin** [comment]
@huddlej good point, done: 8deac077

**Review by huddlej — APPROVED** [review]

**Comment by victorlin** [comment]
woo I'm so excited to use this! No more merge conflicts from adding to `filter.t` in multiple PRs.

If this works well, I'll do the same for other large `.t` files.

**Comment by tsibley** [comment]
Seeing this late, but woo, this is a great direction!

**Pull request merged**
