### PR TITLE
Count insertion/deletion events once in pairwise distances

### LINKED ISSUE #692: distance: Count indels as single events
**Context**

When calculating distances between sequences with insertion or deletion (indel) events, augur distance currently counts each mismatch in a single indel event as separate events. Biologically, this implementation does not make sense, as indels are most likely the result of a single mutational event.

For related discussion, see [the PR to add mutation counts to the ncov workflow](https://github.com/nextstrain/ncov/pull/580).

**Description**

When [calculating distances between nodes](https://github.com/nextstrain/augur/blob/8df4b4d3a500102f7aa3ffb40f78b107c01ae937/augur/distance.py#L201-L274), augur should check for one or more consecutive gap characters (`-`) in each sequence and only count the first of these characters toward the overall distance.

An additional complexity is that a site-specific distance map may specify different weights for the positions affected by an indel event. The distance function must report a single weight value for the entire indel event. Reasonable choices include the maximum weight of all affected positions or the mean weight of those positions.

A mutation-specific distance map may specify different weights for specific mutations that occur at sites affected by an indel. As in the solution above, one could report the maximum or mean weight of any mutation across all affected positions. If the distance map provides specific weights for gaps at sites, the weight for the indel event should be the maximum (or mean) of the gap weights at the affected sites (instead of the weights of all mutations).

**Examples**

Add the following doctests to the `get_distance_between_nodes` function and use these in test-driven development of the functionality proposed above.

```python
"""
Treat a single indel as one event.

>>> node_a_sequences = {"gene": "ACTG"}
>>> node_b_sequences = {"gene": "A--G"}
>>> distance_map = {"default": 1, "map": {}}
>>> get_distance_between_nodes(node_a_sequences, node_b_sequences, distance_map)
1

Use the maximum weight of all sites affected by an indel with a site-specific distance map.

>>> distance_map = {"default": 0, "map": {"gene": {1: 1, 2: 2}}}
>>> get_distance_between_nodes(node_a_sequences, node_b_sequences, distance_map)
2

Use the maximum weight of all mutations at all sites affected by an indel with a mutation-specific distance map.

>>> distance_map = {"default": 0, "map": {"gene": {1: {('C', 'G'): 1, ('C', 'A'): 2}}, {2: {('T', 'G'): 3, ('T', 'A'): 2}}}}
>>> get_distance_between_nodes(node_a_sequences, node_b_sequences, distance_map)
3

Use the maximum weight of gaps at all sites affected by an indel with a mutation-specific distance map.

>>> distance_map = {"default": 0, "map": {"gene": {1: {('C', '-'): 1, ('C', 'A'): 2}}, {2: {('T', 'G'): 3, ('T', '-'): 2}}}}
>>> get_distance_between_nodes(node_a_sequences, node_b_sequences, distance_map)
2
"""
```

### PR DESCRIPTION
**Pull request by huddlej**
### Description of proposed changes    

Counts insertion/deletion (indel) events between sequences as single events instead of counting each gap character independently. Adds logic to support user-defined weights for gaps between specific characters, aggregating weights across all potential mismatches in a sequence-specific distance map, and aggregating weights across all sites in an indel event.

### Related issue(s)  

Fixes #692   

### Testing

Adds doctests for the new expected behavior.

### CODE REVIEW

**Comment by huddlej** [comment]
@benjaminotter No worries if you're too busy to check this out, but I thought you might be interested in this Augur module that calculates pairwise distances between sequences. If you find this interesting, you may want to take a shot at issue #693 which adds a similar kind of functionality to `augur distance`.

**Comment by huddlej** [comment]
@benjaminotter Would you be up for trying to resolve the merge conflicts in this PR? The code this PR modifies overlaps with the code you added to support ignored characters. Tests already exist, so when you get the conflict resolved, you can do the usual `./run_tests.sh` to confirm that everything works as expected.

**Comment by benjaminotter** [comment]
@huddlej, the latest commit resolves the merge conflicts. I used the github interface to do so, which merged `master` into this branch. I then ran the tests locally and all tests passed.

**Comment by huddlej** [comment]
Thank you for making these changes and testing them out, @benjaminotter! I'm sorry I forgot to describe the process we use to resolve these types of conflicts. We generally avoid merge commits from `master` back into a development branch in favor of rebasing the development branch onto master and resolving conflicts during that rebase. This is primarily a Bedford Lab convention (I suspect Richard does not care as much about this, but it's worth checking anyway) that we use to maintain a "clean" git history (so when you look at a graph of the git history, you generally only see development branches like this merged into master with few other merges).

Your edits here were very helpful in confirming the changes that needed to be made, though, and I've used them to perform a rebase onto master and reconfirm that tests passed locally. I'll merge this once it completes the CI.

If you are interested in learning more about how we use git rebase, [the git book has a nice chapter on rewriting history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) and we can also have a quick video chat where I can demo an example of how I use rebase. I didn't get any training in this area of software development during my computer science degree, but it's been super helpful to learn and empowers you to do all kinds of quick git surgery that you'd normally avoid.

**Pull request merged**
