### PR TITLE
Added support for NA epitope and non-epitope mutations

### PR DESCRIPTION
**Pull request by huddlej**
This PR adds support for annotating epitope and non-epitope mutations for neuraminidase.

[Munoz and Deem 2005](https://www.sciencedirect.com/science/article/pii/S0264410X0400636X) defined 45 of NA's 469 amino acids as epitope residues. There were defined as follows:

 * Epitope A (residues 383–387, 389–394, 396, 399, 400, 401, 403)
 * Epitope B (residues 197–200, 221, 222)
 * Epitope C (residues 328–332, 334, 336, 338, 339, 341–344, 346, 347, 357–359, 366–370)
 
These sites are added here in the standard epitope mask format in the flu metadata file `na_masks.tsv` named after the first author of the above paper.

In auspice for a 3 year tree with 2 viruses per month, epitope mutations look like this:

image

Non-epitope mutations look like this:

image

This is my first time working with NA, so if I've missed any caveats about the numbering scheme for amino acids like those for HA, please let me know. I've tested this code with the following commands.

```bash
# Prepare HA and NA
python flu.prepare.py -l h3n2 -r 3y -s ha na -v 2 \
  --file_prefix 'flu_seasonal_h3n2_*segment*_3y'

# Process HA
python flu.process.py --no_mut_freqs \
  --no_tree_freqs --tree_method fasttree \
  --json prepared/flu_seasonal_h3n2_ha_3y.json \
  --epitope_mask_version wolf

# Process NA
python flu.process.py --no_mut_freqs \
  --no_tree_freqs --tree_method fasttree \
  --json prepared/flu_seasonal_h3n2_na_3y.json \
  --epitope_mask_version munoz
```

### CODE REVIEW

**Comment by trvrb** [comment]
Thank you @huddlej. This is really great to see. A couple thoughts:

* Bhatt et al. (https://academic.oup.com/mbe/article/28/9/2443/1007907) use a surface residue epitope mask on NA and get good partitioning of epitope sites showing positive selection and non-epitope sites lacking positive selection:

bhatt

This would be my first stab at an NA mask. Keep Munoz and Deem as a comparison.

NA numbering should start at 1, unlike HA.

* I would test with a 12y tree, which should make selective patterns stand out more. But real proof is definitely in prediction.

**Comment by huddlej** [comment]
I added the sites from Bhatt et al. to the NA masks and colored a H3N2 NA 12y tree by those epitope mutations as shown below.

image

One issue with the Bhatt et al. sites is their sites include residues up to 470, but there are only 469 residues in the NA sequence they reference. They defined surface residues using [PDB data from an H2N2 NA](https://www.rcsb.org/structure/1NN2) and a tool called [ESPript](http://espript.ibcp.fr/ESPript/ESPript/index.php) that parses PDB/DSSP data and outputs “accessible” regions. There is not enough information in the Bhatt et al. methods to exactly recreate their analysis and I was a little concerned about off-by-one issues, so I defined a new surface residues mask based on relative solvent accessibility (RSA) like Juhye did for HA in the DMS paper.

To make the new RSA mask, I converted [the PDB data for the same H2N2 NA](https://files.rcsb.org/download/1NN2.pdb) to DSSP format using the [XSSP web service](http://www.cmbi.ru.nl/xssp/), calculated RSA for NA from the DSSP file using [dms_tools2](https://jbloomlab.github.io/dms_tools2/), and filtered out all sites with an RSA < 0.2 based on Juhye’s threshold for identifying HA surface residues. The advantage of this approach is that it is easy to recreate, but it does not recover all sites from the Bhatt et al. mask.

Looking at the PDB online annotations (shown below), the secondary structure information only starts around residue ~80 and omits a hypervariable region that is not part of the neuraminidase head but is still annotated as on the surface of the virion. The Bhatt et al. sites include the entire hypervariable region in addition to most of the sites I identified with the RSA mask.

image

For completeness, I have included my new RSA sites in the NA masks file and also a mask that combines RSA sites with the experimentally identified sites from Munoz and Deem. I plan to test all these masks in the context of the prediction framework and will write up the results of that analysis separately.

**Comment by huddlej** [comment]
I made the Bhatt et al. mask the default and enabled NA epitope annotations by default for flu builds. I've tested this with the `run_flu.py` script on rhino and found no issues.

**Comment by trvrb** [comment]
This is so cool @huddlej. All the builds worked just fine. I've pushed live to https://nextstrain.org/flu/seasonal/h3n2/na/3y?c=ep, etc...

**Pull request merged**
