### PR TITLE
Fix/parse fix dates

### PR DESCRIPTION
**Pull request by rneher**
addresses #873

### CODE REVIEW

**Comment by rneher** [comment]
@huddlej does this makes sense?

**Comment by rneher** [comment]
I have no preference here. I was initially thinking renaming the function just needs small changes in two places, but then discovered the tests.

**Comment by huddlej** [comment]
I proposed [an alternate solution here](https://github.com/nextstrain/augur/pull/878). Although the original fix only required changing three lines where the `fix_date` argument was referenced, I found another annoying issue with the `fix_dates` function itself and fixed that, too.

**Comment by huddlej** [comment]
Closed in favor of #878

**Pull request closed without merging**
