### PR TITLE
CLI revisions

### PR DESCRIPTION
**Pull request by trvrb**
I went through and did a pass through `bin/augur` (at least through `augur tree`) to look for CLI issues.

This is a small PR that does three things.

#### 1. Change tree `--iqmodel` to `--substitution-model`

I thought it would be super strange to have `--raxmlmodel` and `--iqmodel`. My plan is to just use `--substitution-model` and construct the appropriate flag to pass into IQTREE or RAxML. Currently this only works for IQTREE. But this setup is forwards compatible.

#### 2. Change filter `--categories` to `--group-by` and `--sequences-per-category` to `--sequences-per-group`

This is inline with @tsibley's suggestion. I'm equally happy either way. Does anyone prefer `--categories`?

#### 3. Add consistent shortcuts for commonly used arguments

* `--tree` is `-t`
* `--sequences` is `-s`
* `--alignment` is `-a`
* `--output` is `-o`

### CODE REVIEW

**Comment by trvrb** [comment]
@rneher ---

I did make one functional modification here. I changed default substitution model from `HKY` to `GTR+G`. I did this because I thought that the default behavior (which very few people will alter) should opt for accuracy over speed. As long as alignments are decent length GTR+G should be more accurate than HKY. And especially so for cases like Lassa and dengue, where HKY is more likely to result in long-branch attraction.

**Comment by rneher** [comment]
makes sense. It is important to specify the model though, otherwise iqtree will spend ages testing models. the `+G` is important, I guess. Maybe `+GI`.

**Comment by trvrb** [comment]
Would you believe the model test results to determine a best model to use? I wouldn't have a better strategy. Separate from this PR, maybe we should run IQTREE with model test on flu, TB, Zika, Lassa and Ebola and see what it says. If there's some consistency then go with that model as default.

**Comment by rneher** [comment]
for the builds with short branches, the model doesn't really matter (changes likelihood, but rarely outcome). For builds like Lassa, rate variation is going to be crucial. we could even put in a check that looks at diversity in the alignment and decide based on that what model to use. A test for a few example builds makes sense. For bacteria, the model tests don't really make much sense since the alignments we use are variable sites only...

**Comment by trvrb** [comment]
@rneher ---

This makes sense. It would seem to argue for `GTR` for low diversity datasets (basically no slower than `HKY`) and `GTR+G` or `GTR+GI` for high diversity datasets (slower but should help with long branches).

**Comment by trvrb** [comment]
I've updated default iqmodel to `GTR`. We should revisit whether to make make gamma default.

**Pull request merged**
