### PR TITLE
Version Change Docs & Help

### PR DESCRIPTION
**Pull request by emmahodcroft**
I wasn't sure whether this should go live immediately (it has some comments to-do, so maybe not), and also I included an extension to handle markdown tables, so made a branch instead.

This PR includes a new section in `augur` docs: "Upgrading Augur"

This includes 3 new pages:
- Breaking Changes to augur
- How to Change ‘Export’ Versions
- How Augur Export and Auspice Versions Connect

The first is more generic, and should include breaking changes as we make them, with instructions on how to update the call to get it working. It currently has two, I'm not sure if we need to go backwards, but thought it will be good going forward.

The second gives details on how to move from using `export` to `export v2`. I figure this is going to be a more confusing change for users so we should have a good guide. In future, if we have more versions, we can stream line the v1-to-v2 part and include moving to other versions (which should hopefully be less confusing/more straightforward).
(This may be useful for anyone in the group trying to make the switch/test!)

The third gives some guide as to how to figure out what versions of what work with what. Currently this assumes we are tying export JSON version to Auspice version, but this is currently under discussion. Whatever we choose, we can keep a record of this here, so that it's always easy to find and figure out.

The three tables are definitely redundant, but that's intentional, so it's easy as possible to figure out whatever direction you're trying to go. 

I'll try to answer some of my own questions in 'How to Change Export Versions' soon. We should try to get these complete before we go live with augur v6/export v2/auspice 2.0.

### CODE REVIEW

**Comment by huddlej** [comment]
We discussed this today at the Nextstrain meeting today and agreed it makes sense to merge this branch into the `v6` branch and for internal users to build their own docs locally to refer to this kind of transition guide. This will allow the transition guide to be continually updated as `v6` changes without making those docs public.

**Comment by emmahodcroft** [comment]
👍 This would be great! Esp as currently I have to switch between the two (this and `v6`) to test and to write 😆 .

I have updated them to better describe what's still outstanding and what needs to be done, and to update some decisions we've made since I've last updated. 

I started working on describing how to use `config` file, but won't finish tonight. Will pick up tomorrow, hopefully. 
Some things I cannot address until we clarify the last remaining things about config/CL interactions.

**Comment by jameshadfield** [comment]
👍 @emmahodcroft you can merge into "v6" anytime you like ✅

**Comment by emmahodcroft** [comment]
This is almost done. I am waiting to merge until we have some final things clarified as far as how things override. To avoid having to re-write too often, it's currently a mis-mash of what I wrote during which approach... but this going to be confusing to people using it.

Once we get the override stuff finally sorted, it should be ready to merge as a guide (though almost certainly will not be final). 

**Are we including 'advanced config'/'second config' stuff in `v6`?** I haven't seen anything about it, but I'm holding a section here on it...

**Comment by tsibley** [comment]
FYI, it looks like this was merged into the master branch, not the v6 branch.

**Comment by emmahodcroft** [comment]
🤦‍♀ Sorry...

**Comment by emmahodcroft** [comment]
I'm unsure how best to resolve, and it's past midnight here unfortunately. I'll have to leave it for now, and try to tackle on Wednesday. If anyone can un-merge, I can do-over into `v6`, as branch isn't deleted yet.

**Comment by tsibley** [comment]
No worries, sleep well! I pushed a new commit to master that reverts the merged changes and then merged the branch into v6.

**Comment by emmahodcroft** [comment]
Sorry - I am just now catching up. Thank you for fixing my mistake! Much appreciated! :D

**Pull request merged**
