### PR TITLE
Rate and traits confidence

### PR DESCRIPTION
**Pull request by rneher**
this folds the uncertainty of the rate (either estimated or specified) into the confidence intervals. In addition, the effect of sampling bias on traits inference can be partially mitigated by providing an estimate of how dramatically trait transitions are undersampled.

### CODE REVIEW

**Comment by trvrb** [comment]
@rneher ---

There are some side effects here in terms of rate estimation. Here is the current Zika build with `master`:

master

Here's the current Zika build with `rate_and_traits_confidence`:

branch

I assume you know about this? And that it's intentional?

Also, I'm getting consistent behavior from `master` (TreeTime 0.4.1), while repeated runs with TreeTime 0.5.1 are giving different results.

Repeating `master` I just got 8.72e-4 and 8.72e-4, while repeating `rate_and_traits_confidence`, I just got 5.92e-4 and 6.91e-4, each with different far flung outliers. Compare this to the above for the rerun:

rerun

I think this deserves looking into.

**Comment by rneher** [comment]
yes, I had noticed this. It triggered me to look into the Haiti cluster which just doesn't want to fit the clock. TreeTime 0.5.1 takes correlations in the data more seriously and hence there is a risk that outliers contribute more dramatically. But if the data fit the model, the results should be more accurate. 

this is what I get with the Haiti sequences removed (just pushed that to the nextstrain/zika):
image

**Comment by trvrb** [comment]
My concern was less that the results are different and much that TreeTime was stochastically producing different results.

**Comment by rneher** [comment]
I understand and will look into it. But was this on the same alignment or new alignments? These gappy zika sequences have the tendency to produce alignment artefacts that stochastically generate outliers which should be removed by clockfilter -- but if they are not can cause such wobbling.

**Comment by rneher** [comment]
there is something bizarre that happens when running clock filter. I'll try to get to the bottom of it.

**Comment by trvrb** [comment]
Thanks @rneher.

It looks to me like everything in the PR besides the upgrade to TreeTime 0.5.1 is working really well. I just reverted to older TreeTime. Tests still pass (using new options like `--bias` and `clock-std-dev`). And running on full Zika build works well. I would suggest to merge this into `master` and then approach the TreeTime upgrade as a separate PR. I have a small amount of additional testing I'd like to do. This will remove block from @tsibley's progress.

**Comment by rneher** [comment]
clock-std-dev won't do anything with TreeTime 0.4.1. the bias param should be fine though.

**Comment by rneher** [comment]
I looked into a number of cases. Sometimes it is an obvious misalignment of some sequences -- we know that mafft tends to do that -- which affects both version in a similar manner. Then there is the issue with the Haitian sample. TT 0.5.1 certainly takes them more 'seriously' which distorts the rate estimate. but they should be removed. happy to post-pone merging this. but I don't quite see what needs fixing in treetime (in this respect).

**Comment by trvrb** [comment]
Closing this in favor of rebased version #232.

**Pull request closed without merging**
