### PR TITLE
Remove ebola, lassa, tb, WNV, and zika builds now in their own repos

### PR DESCRIPTION
**Pull request by tsibley**
The live nextstrain.org builds for these viruses are now hosted in their
own repositories:

  • https://github.com/nextstrain/ebola
  • https://github.com/nextstrain/lassa
  • https://github.com/nextstrain/zika

Removing them from augur reduces confusion about what builds are
canonical and reduces the amount of pathogen-specific code + data in
this general-purpose toolkit.

Note that although a nextstrain/WNV repo exists, it is not in use for
the live site; the build/WNV/ directory in here is.

### CODE REVIEW

**Comment by jameshadfield** [comment]
> Note that although a nextstrain/WNV repo exists, it is not in use for
the live site; the build/WNV/ directory in here is.

While the WNV from the augur repo was used to build the JSONs on the live site, the WNV repo produces the same output. Any updates / rebuilds will use the WNV repo, so I think it's safe to remove the WNV build folder from augur.

**Comment by tsibley** [comment]
Ah, great! Thanks for pointing that out, James.

**Comment by tsibley** [comment]
I've updated this PR to remove WNV as well.

**Comment by trvrb** [comment]
This is great. Fully approve.

**Pull request merged**
