### PR TITLE
Improve external command errors

### PR DESCRIPTION
**Pull request by tsibley**
Re: recent discussion on Slack and in today's meeting.

See commit messages for details.

### CODE REVIEW

**Review by huddlej — APPROVED** [review]
This is some beautiful, easy-to-interpret code, @tsibley! I tested out-of-memory errors using a Docker container with memory limited to 1 GB. I used the base Nextstrain image and a local copy of this branch with the CLI’s `--augur` argument as follows.

```bash
$ cd ncov
$ nextstrain shell --augur ../augur .
```

I used this approach to run ncov workflow commands from the CLI's shell.

First, I tried naively running `augur align` on the complete set of ncov sequences from a recent S3 download as follows.

```bash
$ augur align --sequences data/sequences.fasta --nthreads 2 --output test.fasta --reference-sequence defaults/reference_seq.gb
Killed
```

The OS killed this process because it tries to read all of the sequences into memory to support an existing alignment. This is a separate issue that will need to be resolved as part of the new augur read/write interface.

Next, I checked out an older version of the ncov workflow (commit: `bc6f365`) where workflow still used `augur align` after partitioning input sequences into smaller chunks. The partition script also suffered from trying to load all sequences into memory, but after fixing that issue I got the workflow running `augur align` on 1,000-sequence chunks. After running for a while, the workflow died with the following error messages:

```
ERROR: Shell exited 1 when running: mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2 results/split_alignments/53.fasta.to_align.fasta 1> results/split_alignments/53.fasta 2> results/split_alignments/53.fasta.log


using mafft to align via:
	mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2 results/split_alignments/53.fasta.to_align.fasta 1> results/split_alignments/53.fasta 2> results/split_alignments/53.fasta.log

	Katoh et al, Nucleic Acid Research, vol 30, issue 14
	https://doi.org/10.1093%2Fnar%2Fgkf436

Error during alignment
```

Although the process almost certainly died from an OOM error, `augur` did not report this possibility. The beginning of the alignment log output was:

```
nextstrain:/nextstrain/build $ cat results/split_alignments/53.fasta.log
/usr/local/bin/mafft: line 2747:  4157 Killed                  "$prefix/disttbfast" -q $npickup -E $cycledisttbfast -V "-"$gopdist -s $unalignlevel $legacygapopt $mergearg -W $tuplesize $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreads-$numthreadstb $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -g $gexp -f "-"$gop -Q $spfactor -h $aof $param_fft $algopt $treealg $scoreoutarg $anchoropt -x $maxanchorseparation $oneiterationopt < infile > pre 2>> "$progressfile"
```

The end of the log file was a memory reallocation step:

```
Reallocating..done. *alloclen = 73490
```

These outputs show that mafft calls its own subprocesses to perform alignments and it is these child subprocesses that get killed for exceeding memory limits. This means the mafft process that augur calls doesn’t get killed and we can’t know that the process died for exceeding memory use. I tried running mafft directly in the Docker container with a large input dataset and it returns an error code of 1 when its child process gets killed.

Next, I checked out the ncov workflow on `master`, downloaded an existing alignment from S3, and tried to build a global tree from the Nextstrain builds under the same 1 GB memory limitations. After running for a while, the tree step died with the following error messages:

```
ERROR: Shell exited from fatal signal SIGKILL when running: iqtree -ninit 2 -n 2 -me 0.05 -nt 2 -s results/global/subsampled_alignment-delim.fasta -m GTR -ninit 10 -n 4 > results/global/subsampled_alignment-delim.iqtree.log
Command output was:
  /bin/bash: line 1:    92 Killed                  iqtree -ninit 2 -n 2 -me 0.05 -nt 2 -s results/global/subsampled_alignment-delim.fasta -m GTR -ninit 10 -n 4 > results/global/subsampled_alignment-delim.iqtree.log
The OS may have terminated the command due to an out-of-memory condition.

Building a tree via:
	iqtree -ninit 2 -n 2 -me 0.05 -nt 2 -s results/global/subsampled_alignment-delim.fasta -m GTR -ninit 10 -n 4 > results/global/subsampled_alignment-delim.iqtree.log
	Nguyen et al: IQ-TREE: A fast and effective stochastic algorithm for estimating maximum likelihood phylogenies.
	Mol. Biol. Evol., 32:268-274. https://doi.org/10.1093/molbev/msu300

ERROR: TREE BUILDING FAILED
Please see the log file for more details: results/global/subsampled_alignment-delim.iqtree.log

Building original tree took 127.21226000785828 seconds
```

This shows that the actual IQ-TREE process that `augur` started was killed and `augur` could suggest an OOM error.

This PR already improves the user experience quite a bit by avoiding the useless `ERROR: b''`  message and reporting OOM issues when possible. To help troubleshoot error messages during alignment, we could change [the final alignment error message](https://github.com/nextstrain/augur/blob/98c0ea34caf341e1b1ae9ffd335f0f9473f5afbd/augur/align.py#L119) to tell users which log file they could inspect to further troubleshoot. For example, in the alignment error I got above, we could change the output from:

```
Error during alignment
```

to

```
Error during alignment: inspect the log file 'results/split_alignments/53.fasta.log' for more details.
```

**Comment by tsibley** [comment]
@huddlej Thanks, John, for the review and in-depth testing! I took your suggestion to make the `augur align` error message more helpful by directing to the log file and pushed that as e97b84e.

We could probably special-case a workaround for mafft's exit status masking by looking at the log file for "Killed" or similar. This would let us hint at OOM issues in more cases. Thoughts?

**Comment by huddlej** [comment]
A special workaround for mafft could make the user experience a little better for a little more work on our part. Were you thinking of something more robust when searching the first few lines of the log file for `[kK]illed`?

**Comment by tsibley** [comment]
@huddlej 

> Were you thinking of something more robust when searching the first few lines of the log file for `[kK]illed`?

Something more robust would be nice, but I didn't have anything in mind beyond a basic grep. If we were worried about false positives, we could grep a little more specifically for `\d+ Killed` (e.g. ensure that something resembling a PID is present).

**Review by trvrb — APPROVED** [review]

**Comment by trvrb** [comment]
Thanks so much for making these improvements @tsibley and for the careful review @huddlej. This is good to merge in my view.

**Pull request merged**
