### PR TITLE
Filter tips predating first pivot from tree frequency calculations

### PR DESCRIPTION
**Pull request by huddlej**
This PR uses the `node_filter` functionality of the tree frequencies calculations to omit tips that predate the first pivot of an analysis from the frequency estimations.

The included code  ensures that tips filtered by the `node_filter` function do not get included in frequency calculations and makes the filtering of old tips the default for tree frequency estimation.

### CODE REVIEW

**Comment by trvrb** [comment]
Thank you @huddlej. The code looks good to me. I'm testing now and will report back.

**Comment by rneher** [comment]
with this filter, one probably should check for more than one descending clade. If there is only one, just set frequencies to straight 1.0 and move up the tree.

**Comment by trvrb** [comment]
@huddlej: This built just fine for me with nextflu builds. Everything seems to be in working order.

@rneher: Regarding

>with this filter, one probably should check for more than one descending clade. If there is only one, just set frequencies to straight 1.0 and move up the tree.

Does this need to be resolved before this can go in? Or should this be merged and then these optimizations occur?

**Comment by rneher** [comment]
if it runs fine, I think we can merge this. I have had a bunch issues earlier with this (out of bounds errors etc)

**Comment by trvrb** [comment]
Merging now. Has been working fine for me. Producing identical (as far as I can tell) clade level and mutation level results.

**Pull request merged**
