### PR TITLE
Add CITATION.cff file

### PR DESCRIPTION
**Pull request by victorlin**
_[preview](https://github.com/nextstrain/augur/tree/victorlin/add-citation-file)_:

image

## Description of proposed changes

[CFF](https://citation-file-format.github.io) is a file format for citations. This adds a "[Cite this repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)" button on the GitHub repo homepage.

Values retrieved from the JOSS paper page.

## Related issue(s)

https://github.com/nextstrain/public/issues/11

## Checklist

- [x] ~Automated checks pass~
- [x] [Check][1] if you need to add a changelog message
- [x] [Check][2] if you need to add tests
- [x] [Check][3] if you need to update docs

[1]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#updating-the-changelog
[2]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#testing
[3]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#when-to-update

### CODE REVIEW

**Comment by genehack** [comment]
I was curious what this looked like in practice, so I found [a repo that has a CITATION.cff file](https://github.com/amangoel185/hsf-test) — look at the right hand column where the readme, license, code of conduct, etc. are listed.

**Review by genehack — APPROVED** [review]

**Comment by genehack** [comment]
@victorlin might be worth creating issues in nextstrain/auspice and nextstrain/nextstrain.org, at a minimum?

**Comment by huddlej** [comment]
Thank you, @victorlin! This has been on the back of my mind since ~Jan 2021... 😄 Very cool to see it implemented this way, so I can use the same pattern for other projects.

**Comment by victorlin** [comment]
@genehack

> might be worth creating issues in nextstrain/auspice and nextstrain/nextstrain.org, at a minimum?

I chose this repo because it already had a citation snippet in the README. The other two don't. It seems easy enough to just create PRs for those repos, so I'll do that (citing the [Nextstrain paper](https://doi.org/10.1093/bioinformatics/bty407)).

> I was curious what this looked like in practice

There's a preview link at the top of this PR. Just added a screenshot too.

**Pull request merged**
