### PR TITLE
Refactor TiterCollection from TiterModel

### PR DESCRIPTION
**Pull request by huddlej**
Recently, I've needed to perform some analyses of normalized titer data where a tree was not available or necessary. Since the `TiterModel` class tightly couples titer data and a phylogenetic tree, I've split titer-specific methods into their own `TiterCollection` class and made this the base class for `TiterModel`. All of the titer-related methods that remain in the `TiterModel` class require a tree.

Ideally, the `TiterModel` would access `TiterCollection` as an attribute of the model class instead of as a parent class, but this PR's implementation felt like the simplest modification that would affect the least amount of downstream code.

### CODE REVIEW

**Comment by rneher** [comment]
looks sensible to me. but I have one suggestion. The non-existent `node_lookup` is a little ugly. Why don't you remove all refs to `node_lookup` and add a filter function to `TiterCollection`. `TiterModel` could then instantiate a `TiterCollection` and filter this down to all keys in `node_lookup`. I think filtering to titers in the tree is the only reason `node_lookup` is currently required.

**Comment by huddlej** [comment]
That sounds good. I'll give it a shot today. Thanks!

**Comment by huddlej** [comment]
The `TiterModel` now instantiates a `TiterCollection` using prefiltered titer measurements and stores it as a `titers` attribute. With this change you can now access normalized titers via `self.titers.titers_normalized`, for instance.

**Comment by trvrb** [comment]
@rneher: Could you take a look at this and see if it passes your review? I'm sorry, but I have little working knowledge of `TiterModel`.

**Comment by rneher** [comment]
This looks good. nice and clean.

**Comment by trvrb** [comment]
Thanks for the attention here @rneher.

**Pull request merged**
