### PR TITLE
Source canonical Nextstrain environment file for Travis CI

### PR DESCRIPTION
**Pull request by trvrb**
Via @huddlej:

>The canonical environment file is the most up-to-date and does not include conda-forge as a channel. By sourcing this file, we should always get the most recently environment for nextstrain and, in this case, avoid Travis CI timeouts related to long environment solving with conda-forge.

### CODE REVIEW

**Comment by trvrb** [comment]
Should we remove the `environment.yml` file from augur in this case? I feel like we should either depend on Augur conda environment for tests, etc... or push everything to `nextstrain.yml`.

I would think probably safer to just be maintaining a single environment at https://github.com/nextstrain/conda?

Small note that switching from `environment.yml` to `nextstrain.yml` adds ~40 seconds to Conda install as we wait for `pandas`, `nodejs`, `cvxopt` and `git`.

**Comment by tsibley** [comment]
I think it'd be reasonable to depend on the canonical Nextstrain Conda environment, but note that the Travis setup will have to explicitly re-install augur into the environment from the checked out source. Otherwise I believe the environment will include the latest released augur, not the commit being tested.

**Comment by huddlej** [comment]
Isn't the explicit reinstall already happening with the `pip3 install -e .[dev]` command? I'm not familiar with Travis CI, but I assumed that the creation of the `nextstrain` environment in the `before_install` block of the CI config would precede the pip install command from the repo.

**Comment by tsibley** [comment]
Oh I totally missed that! Yes, you are correct @huddlej.

**Comment by tsibley** [comment]
I had seen that the `environment.yml` specified
```
pip:
  - .
```

and thought Travis was relying on that.

**Comment by trvrb** [comment]
@rneher --- What do you think about using central Conda environment throughout? Current Augur docs specify `environment.yml` and I wanted to be sure this was an okay direction for you. I'm okay with either just closing this PR unmerged and keeping `environment.yml` throughout augur or going the PR route of `nextstrain.yml`. I learn towards the latter, especially as we have conflicting install instructions in the current setup that could lead to confusion.

**Comment by rneher** [comment]
moving to a single one definitely makes sense -- but I am getting increasingly confused were all the things are... I guess the only reason to keep this outside of the `augur` repo is the `nodejs` installation for augur. But I don't have strong feelings. 

As you point out, there are a bunch of places in the docs that would need adjusting. When we previously taught nextstrain for Windows users, they often lack `curl`. So it needs to be explicit that they need to install it. 

a few other things: 
 * What part of nextstrain needs git? 
 * cvxopt has been a finiky dependency that is only needed for titers. Do we want it to be part of the default install?
 * I believe python 3.7 works fine.

**Comment by huddlej** [comment]
Getting to some of @rneher 's last points:

  - both curl and wget are available through conda's defaults channel, so if it would help with general use of Nextstrain (e.g., working through tutorials and workshops) we could add those
  - git used to be required by the [old auspice export command](https://github.com/nextstrain/augur/commit/92a2e7934619f6ddbb878e77aac26c6ae56b95c4) and is now only [referenced by developer scripts to build docs or revert releases](https://github.com/nextstrain/augur/search?q=git). We should be able to remove it as a dependency
  - cvxopt installs from conda without any trouble and the latest version in PyPI (1.2.4) installs from pip without any issues. I've confirmed this version still works with the current titers code. We should keep this in the environment file, since it is required by a top-level augur command.
  - I've been testing Zika and flu builds with Python 3.7 while [developing a new Docker base image](https://github.com/nextstrain/docker-base/pull/21) and haven't had any issues

**Comment by huddlej** [comment]
Making a note here that we need to update [the installation docs](https://nextstrain-augur.readthedocs.io/en/stable/installation/installation.html#using-conda) to reference the conda repo YAML instead of the `environment.yaml`.

**Comment by trvrb** [comment]
@kairstenfay just ran into this (https://bedfordlab.slack.com/archives/C0H7C3F0B/p1611191895001200). Can we just remove `environment.yml` from the Augur codebase in favor of https://github.com/nextstrain/conda? The `conda` repo was updated in Nov 2020, while `environment.yml` hasn't been updated since May 2020. 

It looks like @huddlej fixed Travis to no longer use `environment.yml` in this commit: https://github.com/nextstrain/augur/commit/ff91b47f283d0fdf62c8796c398fb4ec2c7c97a5

Is there anything else to be done here besides just deleting `environment.yml`?

**Comment by huddlej** [comment]
Thanks for bumping this, @trvrb! There are still a couple of references to `environment.yml` in the repo related to running tests before a release. These references can be replaced with simpler conda create commands like the Travis CI example.

I'm about to make a release this morning, so it would be simpler to make these changes after the release. I've assigned myself to this issue and moved it to the "Next up" pipeline.

**Comment by trvrb** [comment]
Thanks John! Not urgent, but did want to bump given that this seemed close to complete.

**Pull request closed without merging**
