### PR TITLE
Add support for keeping polytomies in tree inference and refinement

### PR DESCRIPTION
**Pull request by huddlej**
Makes two changes to the augur command line interface including:

  1. the addition of an `--extra-args` argument for `augur tree` that allows
  users to pass arguments directly to their chosen tree building method
  2. the addition of a `--keep-polytomies` flag for `augur refine` that prevents
  TreeTime from trying to resolve polytomies when it increases the likelihood

The first change allows users to specify the IQ-TREE flag "-czb" that collapses
"zero branches", maintaining polytomies in the raw tree. The second change
allows users to keep those polytomies in the time tree. This change is copied
directly from the existing `--keep-polytomies` flag in the TreeTime command line
interface.

### CODE REVIEW

**Comment by huddlej** [comment]
@lmoncla I requested you as a reviewer here since you had requested this feature and I figured you have data you could test the new code against.

For testing purposes, you can clone the repository and run augur tree and refine as follows, after replacing the example paths with your own existing tree data:

```
# Clone augur repo.
git clone https://github.com/nextstrain/augur augur_keep_polytomies
cd augur_keep_polytomies

# Checkout development branch.
git checkout keep-polytomies

# Build tree with collapsed zero branches.
./bin/augur tree --alignment sequences.fasta --output tree_raw.nwk --method iqtree --extra-args="-czb"

# Refine tree keeping polytomies.
./bin/augur refine --alignment sequences.fasta --tree tree_raw.nwk --metadata metadata.tsv --output-tree tree.nwk --output-node-data branch_lengths.json --timetree --clock-filter-iqd 4 --date-inference marginal --date-confidence --coalescent const --keep-polytomies
```

**Comment by trvrb** [comment]
I believe we could just make the IQTREE flag `-czb` be default and avoid having to use `--extra-args`.

**Comment by huddlej** [comment]
That does make sense. I saw this an opportunity to provide a more generic interface to the tree tools, so we don't have to keep updating augur each time something like this comes up. I can see how this could lead to conflicts between our hardcoded defaults and user args though.

**Comment by trvrb** [comment]
Actually... after thinking on this more, I think the best approach to solve @lmoncla's issue would be:

* Keep `--extra-args` (or maybe `--passthrough-args` is more descriptive) in `augur tree`
* Don't include `--keep-polytomies` in `augur refine`. I worry that this road will just lead to exposing all of TreeTime's command line interface in `augur refine`. Instead, make a similar `--extra-args` / `--passthrough-args` flag in `augur refine` that passes through to TreeTime.

I believe that Louise's issue is enough of a one-off issue that it warrants the more flexible solution.

**Comment by rneher** [comment]
How to deal with all of TreeTime's argument will continue to be an issue. But most of them are already exposed and using `--extra-args` for TreeTime is more involved as we don't use it as a command line tool but have to pass them as function arguments through several levels. We might want to use treetime in CL mode at some point, but in this case I believe the `--keep-root` argument makes sense. the `-cbz` flag isn't really necessary since TT will prune short branches anyway.

**Comment by trvrb** [comment]
>How to deal with all of TreeTime's argument will continue to be an issue. But most of them are already exposed and using --extra-args for TreeTime is more involved as we don't use it as a command line tool but have to pass them as function arguments through several levels. We might want to use treetime in CL mode at some point, but in this case I believe the --keep-root argument makes sense.

I see... I forgot about this non-CL aspect. Sound great. I'm assuming the reference to `--keep-root` above is a typo and we should proceed with `--keep-polytomies`.

>the -cbz flag isn't really necessary since TT will prune short branches anyway.

This was my expectation, but I'm not sure it was the behavior we observed. Maybe @lmoncla, can provide example files, but if I remember correctly, she found different behavior based on input with a `-cbz` tree vs without. I'm hazy on the details however.

Or maybe... if Louise runs with `--keep-polytomies` but without `-cbz` we can observe what happens?

**Comment by rneher** [comment]
when inferring timetrees, these branches without mutations should be trimmed: 

https://github.com/neherlab/treetime/blob/master/treetime/treetime.py#L147

otherwise not. Then polytomies are resolved in a greedy way by temporal order and clock-iness (default in augur and treetime). 

(and yes, I meant `--keep-polytomies`)

**Comment by lmoncla** [comment]
Hi everyone, to give some background on why this came up: @trvb and I were working on an analysis that required finding tips with branch lengths ~ 0. I had initially tested this on a tree output from IQTREE (run on its own, not as part of augur). In that instance, adding `-czb` was necessary to keep the polytomies and remove forced bifurcation. When I tried using this same method on nextstrain tree jsons, I was getting different results. However, @jhudd and @jameshadfield helped me figure out that this behavior was due to the difference in meaning of `branch_lengths` between IQTREE and TreeTime, which lead to this issue https://github.com/nextstrain/augur/issues/316. When I switched to using `divergence` when handling the nextstrain tree jsons, I got the behavior I expected without the `-czb` flag or the `--keep-polytomies` flag. So I am no longer using these flags. 

I do however really like the idea of having the option of using extra flags. It was really helpful for me to run IQTREE and TreeTime with and without these flags and compare the results. This helped me figure out that it was not in fact these flags causing the discrepancy, but rather a misunderstanding on my part about the meaning of `branch_lengths`.

**Comment by huddlej** [comment]
I tested the four different combinations of running IQTREE with or without `-czb` followed by running augur refine with or without `--keep-polytomies`. I used a somewhat sparse tree built from simulated data (501 samples total) and counted the number of nodes in the raw and refined trees that had more than 2 children as an approximation of number of polytomies. I also calculated the mean number of children per node with more than 2 children.

* With IQTREE defaults
	* Raw tree: 1 polytomy with 3 children
	* With TreeTime `--keep-polytomies`: 82 total polytomies with 3.61 children on average
	* Without TreeTime `--keep-polytomies`: 74 total polytomies with 3.43 children on average
* With IQTREE `-czb` 
	* Raw tree: 81 total polytomies with 3.60 children on average
	* With TreeTime `--keep-polytomies`: 81 total polytomies with 3.60 children on average
	* Without TreeTime `--keep-polytomies`: 71 total polytomies with 3.46 children on average

I assumed that the variation in TreeTime counts is due to variation in the raw tree based on the `-czb` flag and how that affects IQTREE's calculations.

These results seem to confirm that `-czb` has little effect on the output from TreeTime, but if one were concerned about inspecting the raw tree with or without polytomies, the `-czb` flag is important. I'm inclined to stick with my original formulation of allowing `--extra-args` for tree building and not making `-czb` the default to avoid breaking builds for people who depend on the default behavior.

**Comment by rneher** [comment]
yes, this is the expected behavior. TT resolves polytomies only if they help with the temporal fit. and how that pans out will depend on rooting and the input tree which is stochastic. I agree with keeping the IQ-TREE run with as close to default as possible. Not sure whether `extra-args` should be 'extra-args` or `pass-through-args` or `tree-builder-args` or something else.

**Comment by trvrb** [comment]
Thanks for the detailed investigation @huddlej. I agree with keeping IQTREE call close to default. I also agree that allowing modification to IQTREE call would be helpful. I would lobby for something more descriptive than `--extra-args` however. I think I'm most happy with `--tree-builder-args`. Fully descriptive.

**Comment by huddlej** [comment]
Ok, I've updated the flag in augur tree to `--tree-builder-args` and rebased onto master. This should be ok to merge.

**Comment by trvrb** [comment]
Looks good to merge from my perspective.

**Pull request merged**
