### PR TITLE
cleaner syntax for methods in Process class

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR improves the way in which methods on the `Process` class are defined and called when the methods themselves live in a separate file. They are now called in the same way as methods defined the traditional way.

### CODE REVIEW

**Comment by rneher** [comment]
slightly puzzled why this is an improvement. It looks like you are trying to make the two methods `static_methods` in a way similar to the deprecated old python way. Why not do this:
https://github.com/nextstrain/augur/blob/complete_frequencies/base/auspice_export.py
and that:
https://github.com/nextstrain/augur/blob/complete_frequencies/base/process.py#L628
without pretending they are methods?

**Comment by jameshadfield** [comment]
Ok. Let me summarise the two approaches, then we can pick which one we prefer. I don't think they're very different and am happy to use either one. 

This PR introduces 2 methods (`export_frequency_json` and `export_metadata_json`) into the `Process` class, by defining them in a separate file (for readability) and then setting them as methods in the class body. This is no different to having all the code in the class body. They're not "pretend" methods, and they're not static methods (they both receive `self` as the first param, and use it).

@rneher's way (correct me if I misunderstand) defines `export_frequency_json` as a function (not a method). This function is called from within a class and passed the instance of the calling class (`self`) as the first param (this is referred to as `process` in the function body). This gives the function access to state and methods on the class instance. 

I don't know which way is "more" pythonic or "better". Am happy to learn. Am also happy to move `export_frequency_json` and `export_metadata_json` into the body of the `Process` class, where they would be "more typical" methods if that's clearer.

**Comment by rneher** [comment]
I agree with this summary. what I feel is confusing about the way this PR implements this is

  * the use of `self` outside a class
  * the need for `self.method(self)` which is not the usual pattern. 

Importing them as functions without adding them as attributes (not methods) to the class does exactly the same thing, without unusual patterns.

**Comment by jameshadfield** [comment]
100% agree with the second point (`self.method(self)` is horrible). This PR "improves" this by letting them be called just like any other method - https://github.com/nextstrain/augur/pull/47/files#diff-d349c21fc849fb889fd9f42884e628b1R570

For the first point - I believe `self` has no intrinsic meaning, i.e. if methods are defined outside the class body we could use the word `process` instead of `self`, and the resulting code would be identical.

**Comment by rneher** [comment]
Yes, you are right. this makes them proper methods - sorry. Also you are right that `self` is not a keyword, but there is strong convention. seeing it outside a class is confusing to me. Replacing `self` by process makes this almost identical to the other solution (up to `self.smth(...)` vs `smth(self)`). But either way we are generating merge issues.

**Comment by trvrb** [comment]
I'm going to close this for now (but keep the `improve_python`) branch around  pending discussion between @rneher and @jameshadfield for how best to proceed. This would need rebasing onto `master` at this point anyway and then probably a fresh PR.

**Comment by trvrb** [comment]
I renamed this branch to the clearer `process-methods-syntax`.

**Pull request closed without merging**
