### PR TITLE
More docs

### PR DESCRIPTION
**Pull request by rneher**
This PR adds to the docs using material Emma and I had prepared for the workshops we did. what got added should work for v5 and v6. Documentation of the export step is not yet there and this would need to be very explicit about versions.

### CODE REVIEW

**Comment by jameshadfield** [comment]
Really happy to see more docs coming up, especially in a tutorial-style -- thanks @rneher & @emmahodcroft 

We're going to need to come up with a plan so that (augur's) read-the-docs, nextstrain.org/docs & auspice's docs enhance each other rather than being independent, diverging sources of info. I bring this up here as
* this PR introduces a "Sharing your analysis" (i.e. github community) is similar to https://nextstrain.org/docs/contributing/community-builds
* this PRs "Labeling clades" section is similar to this PR on nextstrain.org https://github.com/nextstrain/nextstrain.org/pull/35

I can see a couple of solutions:
1. Go through the docs periodically adding links between them and making sure things don't conflict
1. Programmatically allow (e.g.) nextstrain.org to source parts of augur's docs, so that these tutorials can appear in both places
1. Others? Doesn't matter?

**Comment by tsibley** [comment]
I enabled this branch as a "version" on Read The Docs so we can preview it here: https://nextstrain-augur.readthedocs.io/en/more_docs/

**Comment by rneher** [comment]
Yes, we should definitely sort this out. I wasn't aware of the PR https://github.com/nextstrain/nextstrain.org/pull/35. The main question we need to address is how much and what kind of docs should live on nextstrain.org. I prefer to have the relevant docs close to the code and this is how we currently do it for auspice and to a growing degree for augur. The split between augur and auspice is of course not a super clean one since you'll need auspice to inspect your augur analysis. 

My suggestion would be:
 * auspice docs live here: https://nextstrain.github.io/auspice/overview
 * augur docs live here: https://nextstrain-augur.readthedocs.io/en/more_docs/index.html
 * nextstrain.org provides the rationale for the project and gives a non-technical overview. In addition, nextstrain.org could source augur tutorials.

**Comment by jameshadfield** [comment]
Brilliant. @trvrb do you also agree? If so, perhaps @misjailcisin could work on taking the nextstrain.org doc content in this direction.

I'm not sure how technically challenging it would be to allow nextstrain.org's docs (currently built from markdown files using gatsby) to source augur tutorials, but @joverlee521 would this be of potential interest for you next week?

**Comment by tsibley** [comment]
To clarify, I think we should prioritize reorganizing the docs, but I don't think we should prioritize auto-importing augur docs into nextstrain.org, which I don't think is necessary.

**Comment by trvrb** [comment]
I concur with Richard's suggestion philosophically (though this sounds way too grandiose). I don't see this as being so different from existing documentation. Nextstrain.org should still explain what Augur is and what a build is, ie https://nextstrain.org/docs/bioinformatics/what-is-a-build, but detailed instructions for running Augur live in the Augur docs. I do think I'd maintain some overlap of install instructions.

The thing that's bugged me here is (of course) the aesthetics of having 3 different styles and 3 different URLs for Nextstrain, Augur and Auspice. I don't have a good suggestion here however.

**Comment by tsibley** [comment]
> The thing that's bugged me here is (of course) the aesthetics of having 3 different styles and 3 different URLs for Nextstrain, Augur and Auspice. I don't have a good suggestion here however.

I think the only reasonable solution to this is not using three different systems for writing docs. There is no particular reason why we couldn't use the same system. For example, it's quite possible to use Read The Docs for Auspice and nextstrain.org and have them be integrated on the same domain. (We have full control of the RTD styles and can make them more on brand.) Porting everything would require quite a bit of initial effort, but going forward, a single doc system would be less work.

**Comment by trvrb** [comment]
That makes sense @tsibley. I have to admit that I really am not into the default Read The Docs aesthetics. But if we could remove ads and skin to be prettier that could work. I definitely prefer the aesthetics / approachability of the Nextstrain.org / Auspice docs. I don't have a good sense for pros / cons for [Sphinx](https://github.com/sphinx-doc/sphinx) (current augur) vs [Docusaurus](https://github.com/facebook/docusaurus) (current auspice).

It does look like the underlying Markdown files are pretty fungible however:
* https://raw.githubusercontent.com/nextstrain/augur/master/docs/installation.md
* https://raw.githubusercontent.com/nextstrain/auspice/master/docs-src/docs/installation.md

**Pull request merged**
