### PR TITLE
Add missing information in 16.0.0 changelog

### PR DESCRIPTION
**Pull request by victorlin**
### Description of proposed changes

Missed some things during the changelog debacle in #959.

### Related issue(s)

_N/A_

### Testing

_N/A_

### CODE REVIEW

**Review by huddlej — APPROVED** [review]
LGTM! I wouldn't call it a debacle though... ;)

**Comment by corneliusroemer** [comment]
Where can I find the debacle :D

**Comment by victorlin** [comment]
Nothing bad, just that there was much internal shuffling since the last release. We only realized last-minute that some of the internal methods are being used by external scripts in other repos, and possibly by other users as well.

Maybe in the future, it would be good to put changelog updates in individual PRs rather than a bulk collection as part of the release process?

**Comment by corneliusroemer** [comment]
I agree, it's best practice to write the changelog in individual PRs, I've started doing that!

**Pull request merged**
