### PR TITLE
docs: Ignore FastTree link for linkcheck

### PR DESCRIPTION
**Pull request by victorlin**
## Description of proposed changes

This URL will occasionally fail and return 403 (broken).

## Related issue(s)

- https://github.com/nextstrain/.github/issues/106

## Checklist

- [x] Automated checks pass
- [x] [Check][1] if you need to add a changelog message
- [x] [Check][2] if you need to add tests
- [x] [Check][3] if you need to update docs

[1]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#updating-the-changelog
[2]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#testing
[3]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#when-to-update

### CODE REVIEW

**Comment by victorlin** [comment]
[Link is ignored](https://github.com/nextstrain/augur/actions/runs/11669146615/job/32490462733#step:9:160):

```
(installation/installation: line    9) -ignored- http://www.microbesonline.org/fasttree/
```

**Review by genehack — APPROVED** [review]

**Review by corneliusroemer — APPROVED** [review]
Yes please :)

**Comment by corneliusroemer** [comment]
I'll merge this already now as it keeps coming up and is a pain, hope this is ok @victorlin

**Comment by victorlin** [comment]
Yes, thanks for merging!

**Pull request merged**
