### PR TITLE
Mask all ambiguous

### PR DESCRIPTION
**Pull request by rneher**
### Description of proposed changes    
some workflows mark parts of the alignment, but standard ML ancestral inference will still pick a "most likely" among the equally likely states at these positions. This PR masks sites without information before exporting.

### CODE REVIEW

**Comment by rneher** [comment]
This PR replaces sites in the root sequence that have `N` in every terminal sequence with `N`. Previously, these were an undetermined nucleotide depending on how rounding errors determined which site is "most likely". 

The root sequence json now looks like this
```
"nuc": "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCTGCATGCTTAGT....
```

The `nt_muts.json` file also contains a `"mask":"111111100000000001000..."` field that is currently unused.

how exactly we handle the mask is up for debate. But I do think we should mask completely undetermined sites.

**Comment by rneher** [comment]
Auspice then displays nothing...

image

**Comment by rneher** [comment]
CI fails bc I added a field to `nt_json` that is not expected by the tests. Can fix this if/after we decide whether we want to export that mask at all.

**Comment by huddlej** [comment]
@rneher I didn't get a chance to fully test this today, but the logic of what you're describing here makes a lot of sense. I'll try to finish my review tomorrow morning and can also push a fix for the test (maybe just to make it less brittle instead of more specific).

**Review by huddlej — APPROVED** [review]
This worked for me as expected with ncov and flu builds. I added a comment to the main masking logic for future us to understand what's happening there and why and updated the functional test to expect the new `mask` key in the ancestral output JSON. When the CI tests have finished, I'll merge this.

**Pull request merged**
