### PR TITLE
Add conda packages and pip packages for running tests

### PR DESCRIPTION
**Pull request by biocyberman**
### Description of proposed changes    
Add missing packages for `pytest` to run successfully on current tests


### Testing
What steps should be taken to test the changes you've proposed?  
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?  
```bash
# cd ~/augur
conda env remove -name augur
conda env create -f environment.yml
conda activate augur
pip install -r dev_requirements.txt
pytest ./tests

```
Return of test run:
```
pytest ./tests                                                                                                                                                                                                                                                                                                                                                !2902
===================================================================================================================================================================================================== test session starts =====================================================================================================================================================================================================
platform darwin -- Python 3.6.10, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: ~/augur
plugins: mock-3.0.0
collected 63 items

tests/test_align.py ................                                                                                                                                                                                                                                                                                                                                                                                    [ 25%]
tests/test_filter.py ..........                                                                                                                                                                                                                                                                                                                                                                                         [ 41%]
tests/test_frequencies.py ................                                                                                                                                                                                                                                                                                                                                                                              [ 66%]
tests/test_mask.py ................                                                                                                                                                                                                                                                                                                                                                                                     [ 92%]
tests/test_utils.py .....                                                                                                                                                                                                                                                                                                                                                                                               [100%]

====================================================================================================================================================================================================== warnings summary =======================================================================================================================================================================================================
~/augur/lib/python3.6/site-packages/Bio/Alphabet/__init__.py:26
~/augur/lib/python3.6/site-packages/Bio/Alphabet/__init__.py:26: PendingDeprecationWarning: We intend to remove or replace Bio.Alphabet in 2020, ideally avoid using it explicitly in your code. Please get in touch if you will be adversely affected by this. https://github.com/biopython/biopython/issues/2046
    PendingDeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============================================================================================================================================================================================== 63 passed, 1 warning in 23.70s ==============================================================================================================================================
```
### Thank you for contributing to Nextstrain!

### CODE REVIEW

**Comment by huddlej** [comment]
Thank you, @biocyberman! These requirements are currently provided by our pip development environment. [Our documentation about how to run tests](https://github.com/nextstrain/augur/blob/master/DEV_DOCS.md#writing-tests) currently recommended installing this environment prior to running tests.

Can you try following the steps in that documentation and confirm whether you are still unable to run the tests without the changes in this PR? Thanks!

**Comment by biocyberman** [comment]
> Thank you, @biocyberman! These requirements are currently provided by our pip development environment. [Our documentation about how to run tests](https://github.com/nextstrain/augur/blob/master/DEV_DOCS.md#writing-tests) currently recommended installing this environment prior to running tests.
> 
> Can you try following the steps in that documentation and confirm whether you are still unable to run the tests without the changes in this PR? Thanks!

Hi @huddlej 
Yes, I did and got an error:

```
./run_tests.sh 
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov=augur --cov-report=html
  inifile: pytest.python3.ini
```

That was because `pip install -e  .[dev]` failed for me. With one more look, it turned out that the command did work because I am running `zsh` shell with `oh-my-zsh`, which interprets `[dev]` as something unexpected. Running `bash -c "pip install -e .[dev]"`  finished successfully. So it would require to update documentation only.

**Comment by tsibley** [comment]
@biocyberman 

> With one more look, it turned out that the command didn't work because I am running `zsh` shell with `oh-my-zsh`, which interprets `[dev]` as something unexpected. Running `bash -c "pip install -e .[dev]"`

You should also be able to just quote that bit in zsh without jumping into bash:

```
pip install -e '.[dev]'
```

**Comment by tsibley** [comment]
I pushed a doc patch in 10c1cb0.

**Pull request closed without merging**
