### PR TITLE
Initial linting pass on much of modular augur

### PR DESCRIPTION
**Pull request by trvrb**
This is a linting pass using flake8 (from PR #169). This PR is separate from whether we choose pylint or flake8.

I have made no functional changes here, just followed the linting rules. This largely caught a bunch of white-space issues like `a=b` vs `a = b`, but did catch unused imports. Pylint would go further than this, but I thought this good for a first pass.

I tested with zika and tb and both are working.

### CODE REVIEW

**Comment by rneher** [comment]
linting is good, but I don't like the way some whitespaces are handled. This one for example:
`if a == b: x`.
I would argue that it is easier to see what is going on if one keeps the comparison together:
`if a==b: x`.
Similarly, I think white space here
`marginal.sort(key=lambda x: x[1], reverse=True)`
is breaking things up that belong  together.

**Comment by trvrb** [comment]
I agree with these two examples. As I was going through and making these suggested changes, I agreed with ~90% of the whitepace changes and disagreed with ~10%. I don't think we should turn off whitespace linting entirely, but would be good to see if the rule can be adjusted.

**Comment by jameshadfield** [comment]
100% agree with Richard. What is our rational for implementing linting?

For me, it's not important (and really not a good idea) to catch errors in things such as `a=2`, `a==b`, `#comment`, `## comment` (which are all currently errors), but to find out things such as "this variable is shadowed" or "don't use [] as a default argument" etc

**Comment by trvrb** [comment]
I like that linting whitespace (and linting in general) creates readable code, for example, parsing: https://github.com/nextstrain/augur/pull/170/files#diff-2437aa922247e9d431a2bd2be13beb74L4, by eye had been nearly impossible for me. Linting forced this to break out into a parsable block of code.

Catching bad practices is of course great as well.

My feeling is that following the white-space rules is an overall significant improvement in readability (while realizing there are cases that definitely hinder). If both @jameshadfield and @rneher are opposed to these rules, let's just run linting with `bad-whitespace` rule disabled. Looking now there didn't seem to be a configuration that would make whitespace linting perform as you would desire.

**Comment by huddlej** [comment]
+1 for PEP-8 whitespace recommendations and linting them as the least important kind of warning.

**Comment by trvrb** [comment]
I'm going to close this PR unmerged and plan to relint with rules disabled per the above discussion.

**Comment by rneher** [comment]
sounds good. its a good idea in general, but if a linter is complaining about all sorts of whitespaces in comments, chances are I'll ignore everything the linter is trying to tell me -- especially if I don't like the outcome in 30% of the cases.  So taking a lighter approach and leaving whitespace to us makes sense to me. Still, whitespace should be used to make code as readable as possible of course.

**Pull request closed without merging**
