### PR TITLE
Install pylint and label dev dependencies

### PR DESCRIPTION
**Pull request by trvrb**
_Edited to restore pylint._

Linting in auspice really helped us to maintain clean code. I'm going to recommend a policy of installing pylint if working on augur. In Atom this just requires clicking a couple buttons to install `linter` and `linter-pylint`.

I've moved pylint and pytest to dev dependencies in `setup.py`. A normal install is the same as before with: `pip3 install --process-dependency-links .`, while a dev install is now `pip3 install --process-dependency-links -e .[dev]`.

### CODE REVIEW

**Comment by jameshadfield** [comment]
:+1: works for me. Note that for those using conda & atom, you have to install `pylint` system-wide to be accessible to atom.

P.S. `pylint augur/*` ---> "Your code has been rated at 4.67/10" 🤣

**Comment by trvrb** [comment]
Sorry about this, but I now think better to use flake8 than pylint. There are a couple reasons for this.

1. flake8 is way faster in testing just now. `time pylint augur/filter.py`gives 40.549s (!!!) , while `time flake8 augur/filter.py` gives 0m0.531s. This was causing Atom linter to crash when using Pylint and making it generally more annoying to work with.

2. Reading online suggested that flake8 gets 90% of the way there and pylint has a bunch of edge cases that need correcting. Pylint is a superset of flake8. Better to correct low-hanging fruit now and later increase stringency if we so desire. There are a lot of linting errors even in flake8.

**Comment by trvrb** [comment]
> Why is flake8 preferred over pylint?

@jameshadfield: You're most welcome to test with both and report back. Okay if you prefer pylint.

This was helpful for me: https://www.reddit.com/r/Python/comments/82hgzm/any_advantages_of_flake8_over_pylint/

**Comment by jameshadfield** [comment]
If you're using conda, running `atom --new-instance` from within that environment allows atom to use the appropriate flake8 version

**Comment by trvrb** [comment]
Are you getting pylint to run on `filter.py` in less than 40 seconds? Is there some flag to improve this?

**Comment by jameshadfield** [comment]
For me `pylint augur/filter.py`:
```
real	0m7.451s
user	0m6.961s
sys	0m0.196s
```

And i presume this'll be even faster if we were to remove rules such as
> C:135, 0: Exactly one space required after...
> C: 67, 8: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
> C:135, 0: Line too long (102/100) (line-too-long)
which constitute the majority of the errors displayed

**Comment by trvrb** [comment]
Following from here: https://github.com/PyCQA/pylint/issues/1416, I'm seeing 4 seconds for pylint 1.6.5 and 40 seconds for pylint 1.9.2.

**Comment by trvrb** [comment]
Commenting out those rules doesn't improve performance under 1.9.2 for me. I'm assuming this is because they are dead-simple to test for, unlike more complicated rules.

**Comment by trvrb** [comment]
I just removed the flake8 commit and will experiment with updating pylint rules.

**Comment by trvrb** [comment]
See how you feel about things now @jameshadfield. Note that I pinned `setup.py` to pylint 1.7.6 because anytime more recent was giving the poor performance issue and taking ~40 seconds to lint `filter.py`. 1.7.6 is taking ~5 seconds and giving the same output.

**Pull request merged**
