### PR TITLE
Find & Annotate DRM Sites

### PR DESCRIPTION
**Pull request by emmahodcroft**
This adds `find_drm.py` which finds specified DRM sites (including on ancestral seqs if provided), annotates them onto nodes, and generates colours for them.
At the moment this is pretty TB specific (expecting a non-standard file format and only TB drug names) but can be modified to apply to HIV (or anything else). However, it's of big interest in TB datasets, so important to have.

A couple of notes:
- Colours are generated by the script. At the moment this works by passing in your `color.tsv` file (with country & other trait colours) and the colours generated for DRM are added to this file, with a new version being written out. This is then what should be passed to `export`
- This currently only works with VCF input but should be modified to work with Fasta
- At the moment this requires annoying modification of `config.py` to include all the fields generated by the script in order to colour by them. I didn't bother changing this; if the plan is to bundle generation of `config.py` into export it can be tackled once there. However if it would be better to deal with now, I can change it to modify and write out a new version of `config.py` as it currently does with `color.tsv`. 

Unfortunately the Lee et al. data (the TB dataset currently on github) has no DRMs and so running this does nothing. I'll try and trim my Walker et al. dataset down to published sequences which I can then provide for testing this bit.

### CODE REVIEW

**Comment by trvrb** [comment]
Thanks for the PR @emmahodcroft. A couple fairly high-level thoughts:

1. Why take `--colors` as part of `augur find-drm`? I would think of this acting exactly like `augur traits` in that `augur find-drm` would produce a node data JSON specifying DRM scores and genotypes for every tip in the tree. Ah, I see. This is basically what you're doing. In this case, I don't really understand why the colors export is necessary.

You should be able to leave out the colors export and have auspice treat the trait `Drug_Resistance` as an ordinal color map and it should pick an appropriate gradient to match traits `0`, `1`, etc...

Ie I believe that `get_N_HexCol` (`Auto-generate colours for DRMs to prevent users having to do it`) should be the purview of auspice and not deeply embedded in particular augur modules.

If you don't like these colors, then the original `config/colors.tsv` should be edited. This is inline with how `augur traits` behaves, ie you don't give `augur traits` a color map, you instead edit `config/colors.tsv`.

Same story with traits like `Rifampicin`. Auspice should pick a color ramp by itself which can be overridden by adjusting `config/colors.tsv`.

If you want a smarter override than manually specifying colors in `config/colors.tsv` I believe this should be wrapped into `augur export` so it can apply to other traits not just DRMs.

2. I think that `augur find-drms` should maybe be something more generic like `augur phenotypes`. For Zika, there's an interest in particular mutations possibly associated with microcephaly. For avian flu, there's high-path vs low-path determined by a canonical mutation to HA cleavage site. It's the same basic thing of having a genotype-to-phenotype map prespecified and determining traits from this map.

As it doesn't seem that `DRMs.txt` is standard format, I'd suggest we figure out what format we think is best.

Small particulars:

3. You should be able to call `augur find-drm` rather than `augur find_drm`.

4. Running the PR branch on walker data gave me a `results/colors.tsv` that had Windows line endings and in which the DRM color mapping was not split onto multiple lines, like so:
```
country	kenya	#9494b8    Drug_Resistance	0	#b23535  Drug_Resistance	1	#b2b235
```
I think this is just a line endings issue. Other files in `results/` all have Unix line endings. Ah... I see, the problem goes away when the file `data/color.tsv` is switched to Unix line endings.

**Comment by emmahodcroft** [comment]
Thanks @trvrb - so I actually hadn't considered having auspice assign colours, and I agree this is a better solution. I'm travelling back to Basel tomorrow but I will look into this as soon as I can and make changes.

2. Yes, I'm happy to make this more generic so it can be applied to other scenarios

I'm also happy to come up with a file format that can be more widely applied; I'll have a think on this.

4. I'm running Windows with the new built-in Ubuntu, but my text-editing is in the Windows bit, so this is a bit of an issue for me. I have just switched to Visual Studio Code which I imagine will make it easier for me to force this kind of thing, and will also try and run through my existing input files to check for this. However, it is definitely me (input files coming from Windows) rather than the code!

**Comment by trvrb** [comment]
Thanks @emmahodcroft. These traits still need to have an explicit `color_options` in `meta.json`, but they don't need an explicit `color_map`. For example:
```
  "num_date": {
   "menuItem": "date", 
   "type": "continuous", 
   "legendTitle": "Sampling date", 
   "key": "num_date"
  }, 
```
Export should handle this currently.

As for generalizing, I'm not 100% sure it's the best path forward, but I think worth investigating. My thought here would be to work with @huddlej on the command line interface. John is currently computing "epitope mutations" in flu using https://github.com/nextstrain/augur/blob/master/base/scores.py. This is very similar like your use case to calculate `Drug_Resistance` trait. This takes in a mask file that lists epitope sites in the protein and calculates the number of mutations at epitope sites. It's a bit different from what you have in counting mutations from root rather than counting genotype matches.

I would say that if there's a convenient input file format and command line interface that serves both well without being too hairy, to combine. If this is seeming to work at cross-purposes then I'd keep `find-drm` separate.

Hmm... I'm now realizing that a single `augur phenotypes` probably won't serve all purposes. Another solution might be to have separate `augur drm-scores` and `augur epitope-scores` modules that are distinct in the code but semantically similar and attempt to use similar command line interfaces.

This would suggest a separate `augur lbi-scores` to compute the LBI trait across nodes. Or `augur lbi`.

Rather tricky to figure out this partitioning.

I would say to make this PR work, merge and then revisit combining modules.

**Comment by emmahodcroft** [comment]
Hi @trvrb - 
1. Allowing auspice to do the colouring works, so I've changed this. 
For 'Drug Resistance' the legend numbers are out-of-order, but this could perhaps be modified in `auspice` at some point to look pretty. 
image

For `DRMs.txt`, I've stripped this down to the fields I use (position, base change, AA change, drug). The AA change we could calculate internally, but it would mean sending the .gb or .gff file back in to get strand and reading frame. I've left this for the moment but this could be changed or made optional. 

3. For 'find-drm' vs 'find_drm' - I've made it so users call `find-drm`, but it seems that having the dash in the import isn't working. So at the moment the file itself, import, and 'func' are `find_drm`, while the call is `find-drm` - I'm not sure if this is fine, or confusing. I'm happy to change the name entirely if there's something more suitable, or leave as-is with thoughts to combining or making more similar to other phenotype things in future (which may change the name again). 

Getting the `config.json` generated in `export` (eventually) will be important here, I think, as you don't know how many drugs to include until after running `find-drm`, which is a bit of a pain for the user.

**Comment by jameshadfield** [comment]
😱 auspice shouldn't do that. I'll fix it.

**Comment by trvrb** [comment]
Thanks for the revisions @emmahodcroft. A couple suggestions:

1. I'd rename the call to `--drms` to `--mapping`. At it's heart you need mapping of genotypes to drug resistance phenotypes.

2. I'd reduce this mapping file further and make it more explicit. Right now you have:
```
GENOMIC_POSITION	ALT_BASE	SUBSTITUTION	DRUG
761101	C	Q432P	RIF
```
It shouldn't actually matter that it's nucleotide C at site 761101. It matters that it's amino acid P at site 432 of gene rpoB. There are multiple ways to get to this P.

I would generalize this as:
```
GENE	SITE	MUTATION	DRUG
rpoB	432	P	RIF
```
This is easily keyed off of output of `translate`. Safe to use this sort of nucleotide matching with TB which mutates so rarely, but I suspect that HIV would need AA matching.

3. Seems strange to me to have the mapping of `RIF` to `Rifampicin` take place inside the `find_drm.py` module. What happens when people have drugs not on this list? Seems analogous to `lat_longs.tsv` which lives outside of `export.py`. However, here I'd go for the simpler what-you-see-is-what-you-get and actually ask that the input file be:
```
GENE	SITE	MUTATION	DRUG
rpoB	432	P	Rifampicin
```
If you want auspice, etc... to refer to this as `Rifampicin`. Easy to be explicit here.

**Comment by emmahodcroft** [comment]
@trvrb This all sounds good to me; I'll get working on it :)

**Comment by emmahodcroft** [comment]
I have renamed to `mapping` and replaced the drug names with the full names as suggested.

@trvrb What I hadn't considered is that some of the DRMs are in intergenic regions, so using the output of translate won't work here. This won't be a problem for HIV.

I'm working on making two arguments. Using `--nucleotide` you can pass in a file with the basic format:
```
GENOMIC_POSITION	ALT_BASE	DRUG
6505	T	Fluoroquinolones
6505	C	Fluoroquinolones
6618	A	Fluoroquinolones
```
And instead of displaying the AA mutations in auspice for each drug selected, it will display the nuc mutation:
image

If you give include an optional 'AA' column (was previously 'SUBSTITUTION'), it will display the AA change as before:
image


Using `--amino-acid` you will be able to pass in a file in the format you specify above (and need to also supply a translation file). However, it won't detect DRMs (etc) outside of the genes you've translated (if you specify a list of genes to `translate`) or in intergenic regions. 
Currently working on this.

**Comment by emmahodcroft** [comment]
Summary of options:
- `--nucleotide` can handle two types of file above where mapping is done by nucleotide position
- `--amino-acid` takes in a file of the format below. The user must also pass in `--translate-vcf` (translation of all the sequences) and `--translate-ref` (reference seqs for each gene translated) (both generated by `translate` with VCF input)
- `--count` can be either 'trait' (default) or 'mutations' to count either # of traits on each node (ex: number of drugs this seq is resistant to) or number of mutations on that node
- `--label` is the label to be used for the above count (ex: 'Drug Resistance' or '# Mutations')

AA file format:
```
GENE	SITE	ALT_AA	DRUG
gyrB	461	N	Fluoroquinolones
gyrB	499	D	Fluoroquinolones
rpoB	170	F	Rifampicin
rpoB	359	A	Rifampicin
```
When using this format, the gene is added to the legend:
image

AA format should only be used with viruses (I imagine) as it won't find any mutations in intergenic regions or in non-protein-coding genes (ex: rrs in TB)

**Comment by rneher** [comment]
I feel `mapping` is a pretty bad name for this as it has a very well defined meaning in bioinformatics that is very different from what is happening here. my proposal is `sequence-traits` in analogy to `traits`. these really are traits derived from sequence based on a list of mutations that correspond to particular features. happy to consider other names though.

other than that, I stream-lined this and made generic.

**Comment by rneher** [comment]
would be good to converge on nomenclature etc here. I made a number of substantial changes, hoping to make this more general and streamlined. But there doesn't seem to be a very good name for this step. It essentially derives phenotypes/traits from features in the sequence. It is hence similar to the `traits` module, but the ancestral inference is already done via the ancestral sequence inference.

**Comment by trvrb** [comment]
@rneher and @emmahodcroft ---

Thanks for all efforts here. I definitely like calling this `sequence-traits` in analogy to `traits`. Seems suitably generic. I also like `--features` instead of `--mapping`. A few thoughts:

1. Could you please include this in `tests/builds/tb` and also update `builds/tb`? The test build doesn't include `find-drms` or `sequence-traits`. And the full build at `builds/tb` has a call to `find_drm` which is now outdated. I don't have an easy way to test this otherwise.

2. I had imagined that this would take the output of `augur translate` and `augur ancestral`. Both produce JSON files. But you ask for a FASTA alignment `--alignment`. Note that `augur translate` takes `--ancestral-sequences` and not `--alignment`. I think that the function call here should work in analogous fashion to `augur translate` but take the JSON output of `augur translate` eg `aa_muts.json`. It's possible I'm missing something here.

3. Rather than having two "modes" eg default and `--amino-acid`, what about allowing two different file intputs, call these `--nucleotides` (that takes `nt_muts.json`) and `--amino-acids` (that takes `aa_muts.json`). You then wouldn't have the somewhat funny nucleotide features format that looks like `6505 T D461N Fluoroquinolones` which is duplicating functionality in `augur translate`. I'm not sure if this is definitely better, but something to consider. 

So my suggested interface:

* Keep `--features` (that can contain both aa features like `gyrB 499 D Fluoroquinolones` and intergenic nucleotide features like `nuc 6505 T Fluoroquinolones`)
* Repurpose `--alignment` into `--nucleotides` and `--amino-acids`
* Drop `--amino-acid` toggle
* Everything else is the same

**Comment by emmahodcroft** [comment]
> Could you please include this in tests/builds/tb and also update builds/tb? The test build doesn't include find-drms or sequence-traits. And the full build at builds/tb has a call to find_drm which is now outdated. I don't have an easy way to test this otherwise.

The public dataset (Lee et al/Nunavik) we've been using has no DRMs, so isn't great to test this. I've added a small dataset to `tests/builds/tb_drm` from other published sequences that have DRMs. I've included the `sequence-traits` call in `builds/tb`, but as there are no DRMs nothing comes from this. 

> I had imagined that this would take the output of augur translate and augur ancestral. Both produce JSON files. But you ask for a FASTA alignment --alignment. Note that augur translate takes --ancestral-sequences and not --alignment. I think that the function call here should work in analogous fashion to augur translate but take the JSON output of augur translate eg aa_muts.json. It's possible I'm missing something here.

At the moment, only VCF-input is supported, but these VCFs do come from `ancestral` (for nuc) and `translate` (for AA). 
We should be able to take in JSON input both for 'VCF' and 'Fasta' input, as we should be able to figure out the sequence at each node from the mutations in the JSON, tree, and root sequence - but we don't currently store the root sequence. Richard and I propose that we merge this PR, and once we've decided on a way to include the root sequence (discussed [here](https://github.com/nextstrain/auspice/issues/616)) we should be able to switch over to taking JSONs for runs that start with Fasta or VCF input originally, which will make this quite tidy.

>Rather than having two "modes" eg default and --amino-acid, what about allowing two different file intputs, call these --nucleotides (that takes nt_muts.json) and --amino-acids (that takes aa_muts.json). You then wouldn't have the somewhat funny nucleotide features format that looks like 6505 T D461N Fluoroquinolones which is duplicating functionality in augur translate. I'm not sure if this is definitely better, but something to consider.

>Keep --features (that can contain both aa features like gyrB 499 D Fluoroquinolones and intergenic nucleotide features like nuc 6505 T Fluoroquinolones)

I combined these two ideas and have removed the `--amino-acids` flag and added `--ancestral-sequences` (for nuc alignment) and `--translations` (for AA alignment). I was a little concerned that `--nucleotides` and `--amino-acids` sounded more like lists of sites than a JSON or alignment to be provided. 

To allow the type of file you suggest, I've modified the code so the user can provide **both** `--ancestral-sequences` and `--translations`, along with a slightly modified version of the features file where both AA and nuc changes can be specified:
```
GENE	SITE	ALT	DISPLAY_NAME	FEATURE
gyrB	461	N		Fluoroquinolones
nuc	1472358	T	rrs: C513T	Streptomycin
nuc	1673425	T	fabG1: C-15T	Isoniazid Ethionamide
ethA	175	T		Ethionamide
```

Here the flexibility of 'DISPLAY_NAME' is better shown - it can be anything you want to use to distinguish mutations in the legend. If it's just the AA change, as in the example you give, it does replicate `translate` a bit, but without having to do any translation (either in `sequence-traits` or having to have run `translate`) - but one can put anything else (like gene, above) in there too. Here, DISPLAY_NAME for the fabG1 mutation mimics the label that would be generated for a 'normal' AA mutation (ethA), which prevents it showing up as `C1673425T` in the legend.
image


The previous formats of file, along with just `--ancestral-sequences` or `--translations` can also still be used.

**Pull request merged**
