### PR TITLE
add coverage config file

### PR DESCRIPTION
**Pull request by willingc**
Addresses #485

### CODE REVIEW

**Comment by elebow** [comment]
Should we add `htmlcov/` to `.gitignore`?

**Comment by willingc** [comment]
@elebow Yes, we should. Good catch. I did add it in an earlier open PR #486 https://github.com/nextstrain/augur/pull/486/files#diff-a084b794bc0759e7a6b77810e01874f2

Perhaps I should add here as well.

**Comment by tacaswell** [comment]
We need to get this PR and #486 in.  We also need to add the upload call to push stuff to codecov and someone with write privileges to set up the integrations?

**Comment by huddlej** [comment]
@willingc @tacaswell This seems like a great direction. Would either of you be able to link to an example of how you're using codecov integrations on GitHub currently?

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/blob/0e4685b8d89671bdf4a291a395a5ea11e503fe76/.travis.yml#L191  <- that is how we invoke pytest for Matplotlib.  

https://github.com/matplotlib/matplotlib/blob/0e4685b8d89671bdf4a291a395a5ea11e503fe76/.travis.yml#L215 <- that is the line that uploads 

If you look at any of our PRs (say https://github.com/matplotlib/matplotlib/pull/16960) you will see 3 entries from codecov in the checks.

We also get status reports that look like https://codecov.io/gh/matplotlib/matplotlib

**Comment by huddlej** [comment]
Thank you, @tacaswell! @trvrb is on board with this, so I am going to merge this. We will follow up about actually adding the integration to the Travis.

**Pull request merged**
