### PR TITLE
Detect Tab-Delim Lat-long Files

### PR DESCRIPTION
**Pull request by emmahodcroft**
This won't solve the whole tab-delim problem but I am currently working with a dataset where some location names have spaces, and need to match them up to self-generated GPS locations. 

Partially following @trs idea, I've added a line (in `v6`) to `read_lat_longs` in `util.py` which splits by tab if it detects tab in the line, else continues to split by whitespace (as was default until now). 

This allows traits to include spaces.

Shouldn't affect anything else.

### CODE REVIEW

**Comment by tsibley** [comment]
This does bring along some backwards-compat breakage for lines with mixed tabs and spaces as column delims. Those lines work in augur v5 but will not with this change. For example, this file will be parsed incorrectly: https://github.com/nextstrain/tb/blob/57e83f71793ca992ca57dd3d98293c75d043856a/config/lat_longs.tsv. There are other examples outside our group as well, like https://github.com/adoebley/rabies/blob/97dd06490c32d953fa16cbc073742fc38d2ea5cd/config/lat_longs.tsv.

**Comment by emmahodcroft** [comment]
Well dang. I can add underscores to or our dataset and we can revert if we
need. Unless there's a way we can detect this?

**Comment by tsibley** [comment]
I think the heuristic needs to be at the file level, not per line. Standard backwards compat methods involve detecting something that's always present in one format but never present in the other. Often this is something added by the new version. With that in mind, how about checking if the first line is a tab-delimited set of expected column names? If it is, then require and use tabs as delimiter for rest of the file. If not, then assume its not a header row and process all lines as whitespace delimited. Something like this:

```python
if {"scale","name","lat","lng"}.subset(lines[0].split("\t")):
    # new version, all subsequent (non-comment, non-empty) lines are tab-delimited data
else:
    # old version, all (non-comment, non-empty) lines, including the first, are whitespace delimited data
```

**Comment by tsibley** [comment]
This provides a clear, easy-to-document upgrade path from old-style `lat_longs.tsv` to the new-style: you add a header line and make sure all rows are tab delimited.

The header row provides a measure of self-documentation, allows columns to appear in any order, and allows augur to ignore additional data columns which is useful if you're pulling from an existing location dataset.

**Pull request merged**
