### PR TITLE
Supply command line arg `--title` as single string

### PR DESCRIPTION
**Pull request by jameshadfield**
@emmahodcroft  please make sure this is an improvement from your perspective!

### CODE REVIEW

**Comment by emmahodcroft** [comment]
So - I think there's a snakemake thing going on here that's making this more complicated! 

This works (as in your zika test):
```
shell:
  """
  augur export v2 \
    --title "Phylodynamics of Enterovirus D68 - v2" \
  ...
```

This does not work:
```
params:
  title = "Phylodynamics of Enterovirus D68 - v2",
  auth = "'Emma Hodcroft' 'Robert Dyrdak'",
  ...
shell:
  """
  augur export v2 \
    --title {params.title} \
  ...
```
Error: `augur: error: unrecognized arguments: of Enterovirus D68 - v2`

It seems to be the only one that doesn't work like this, in a straightforward manner.

This does work (single quotes inside of double quotes):
```
params:
  title = "'Phylodynamics of Enterovirus D68 - v2'",
  ...
shell:
  """
  augur export v2 \
    --title {params.title} \
  ...
```

So I suppose we can just tell users to use double and single quotes. But it seems like this is likely to be a point where people get stuck a lot...

Similar thing happens with `--maintainers`. This works as expected (single quotes surrounding each name, inside double quotes):
```
params:
  auth = "'Emma Hodcroft' 'Robert Dyrdak'",
  ...
shell:
  """
  augur export v2 \
    --maintainers {params.auth} \
  ...
```

Putting directly in the CL like this:
```
shell:
  """
  augur export v2 \
    --maintainers "'Emma Hodcroft' 'Robert Dyrdak'" \
  ...
```

Results in this:
image
(they are one link)

Telling people to do things differently whether using CL or putting it in `params` in snakemake seems dangerous (in that people will mess this up and won't know why it doesn't work). Is there a better way we can handle this?

**Comment by huddlej** [comment]
I'm not fully up to speed on the context of the v6 modifications, but from the perspective of writing Snakemake rules, I would expect the rule to look like this:

```
params:
  title = "Phylodynamics of Enterovirus D68 - v2",
  ...
shell:
  """
  augur export v2 \
    --title "{params.title}" \
  ...
```

If the augur command supports an argument with whitespaces like titers or maintainers, we can ask users to run the command with just the double quotes as in the rule above. The double quotes in the params is how we let Snakemake know the title is a string, but the param could also be defined in a separate config file like so:

```
{
    "title": "Phylodynamics of Enterovirus D68 - v2"
}
```

And the rule would look like this:

```
params:
  title = config["title"],
  ...
shell:
  """
  augur export v2 \
    --title "{params.title}" \
  ...
```

In either case, the double quotes around `{params.title}` in the rule's shell command should let us avoid asking users to enter two types of quotes.

Maintainers seems a little more complicated because whitespace is used to separate multiple maintainer arguments and the first and last names of each individual maintainer. The way I've usually seen this implemented is to reuse the `--maintainers` flag for each argument like so:

```
shell:
  """
  augur export v2 \
    --maintainers "Emma Hodcroft"
    --maintainers "Robert Dyrdak" \
  ...
```

argparse should know how to convert the multiple arguments into lists of whitespace-containing strings. We can make Snakemake auto-generate those arguments for however long the maintainers list is.

**Comment by jameshadfield** [comment]
@emmahodcroft @huddlej re: title not quoted when it's a param - snakemake (python) has a `:q` string formatter to fix this, but unfortunately the onus is on the person writing the snakemake file (or us writing the example builds & tutorials!)

```
    params:
        title = "Quoted title via snakemake params"
    shell:
        augur export v2 --title {params.title:q} ...
```

**Comment by jameshadfield** [comment]
re: maintainers. I agree this is more complicated -- for both whitespace & associating a URL with them. 

@huddlej with the multiple `--maintainers` flags, would you have corresponding multiple `--maintainer-urls`?

Re: whitespace & current `--maintainers` behavior, this is (the best?) way to do it in snakemake:
```
    params:
        maintainers = ["Person One", "Person Two"]
    shell:
        augur export v2 --maintainers {params.maintainers:q} ...
```

**Comment by emmahodcroft** [comment]
I'm disappointed there isn't a better way to do this where users don't have to remember such finicky details. Is it completely not an option to not bundle up multiple args (`nargs='+'`) and make them a string? (Stripping outside quotes if needed?) 

I accept this may not be canonical but I think usability should overrule that when it gets so fiddly. Passing a multi-word string as an argument in a similar manner in CL and snakemake both should not be so difficult!

I think having to ask users to remember to double-quote or use `:q` (but only sometimes!) for something so simple is... 🙄

**Comment by jameshadfield** [comment]
> Passing a multi-word string as an argument in a similar manner in CL and snakemake both should not be so difficult!

💯 Agree!

>  Is it completely not an option to not bundle up multiple args

This solution -- for me -- has some pretty big problems. Are they bigger than my solution? Not sure. But this _doesn't_ do what you think it should! 
```
augur export v2 ... --title Zika in Central & North America ...
```

**Comment by rneher** [comment]
As long as we run augur as shell commands, we will have to "" strings or escape whitespace, &|*? etc. I don't think `"{params.title}"  or :q is too bad.

**Comment by emmahodcroft** [comment]
> This solution -- for me -- has some pretty big problems. Are they bigger than my solution? Not sure. But this doesn't do what you think it should!

Ah ha. I see the problem. 😖  Sorry for my slow uptake. 

I shall add this argparse shortcoming (IMO) to my list of things to intermittently grumble about forever and suggest we pin somewhere a TODO to make this super-duper ultra clear in docs and tutorials!

**Comment by trvrb** [comment]
I agree this is frustrating. However, I think opting for "proper" command line interface is better than capitulating to Snakemake's design. We could also consider making an issue / putting in a PR into Snakemake to make a global flag for `:q` delimiting.

**Comment by rneher** [comment]
I still think that everything that is going on here is perfectly expected behavior. Command line arguments are whitespace separated. If we want to use them to input generic text, this needs to be quoted or escaped in some way and it is better to do this explicitly than to generate unexpected behavior in other places. (say somebody had a `params.flags = "--option1 -xls" if x else "--option2 -xgd` -- not recommended practice but certainly possible, this would break in the weirest ways)

**Pull request merged**
