### PR TITLE
Validate meta & tree JSONs against current modular export

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR introduces `augur validate` which takes a tree and / or meta data JSON and (a) validates it agains the JSON schema(s)  and (b) checks for internal consistency.

### JSON schemas
Following draft-06 of [JSON Schema](http://json-schema.org/) we now have a JSON schema for the tree and metadata JSONs.  I’ve added as many descriptions and comments as possible to make it more human readable. This schema is designed to work with the currently produced output, not necessarily the desired output.

Recent work has allowed Auspice to work without a metadata JSON at all. Therefore, technically, none of the fields in the metadata schema are enforceable or required. I’ve instituted a second “recommended” schema for the metadata which enforces certain fields.  Which fields we require is up for grabs - see `augur/data/schema_recommentations.json`

### Internal consistency checks
There are certain things which one can’t validate using the schema alone (at least, I don’t think you can). For instance, the `color_options` specified in the `meta.JSON` should appear as keys on at least one node in the tree JSON. I’ve written python code to check this after the JSONs have been checked against the schemas.

### Errors vs Warnings
Errors cause a non-zero return value, while warning will still return zero. Both are directed to STDERR. Failure to validate against the (base) schemas is an error. Failure to validate against the recommended metadata schema (which enforces certain fields) is a warning. Similarly for the internal consistency checks,  things such as defining a `color_option` in meta which doesn’t appear in the tree is an error, while defining a color value (hex) which doesn’t appear in the tree is only a warning.

### Schema versioning
Currently the metadata schema carries a  `version` property of `0.1`. This can be incorporated into the `meta.JSON` itself (see extensions, below).

After discussions with Trevor & John, we decided to use a 2-digit server-like system where changes in the second part indicate backward compatibility, and changes in the first are breaking (for auspice). Auspice should read this version and decide whether to proceed, raise an error, or attempt to patch/modify the JSONs to update them appropriately. This is all beyond the remit of this PR.

### Current “errors / warnings” in modular-produced zika JSONs
No errors, some minor warnings such as 
> `WARNING:  Color option "country" specifies a hex code for "taiwan" but this isn't ever seen on the tree nodes.` etc

### Notable “errors / warnings” in non-modular-produced JSONs
* *ev_d68* defines “pending” as an accession (currently an error)
* we have accessions such as “EM_COY_2015_014098”, “Washington_outbreak_7” which are errors under this schema
* many `paper_url`s are written like “https_//…” (currently errors)
*  There are lots of errors which seem legitimate problems. For instance, with “flu_seasonal_h3n2_ha_3y”:
	* `ERROR:  Author "instituto_adolfo_lutz" defined on a tree node but not in "author_info”`…
	* `ERROR:  Meta JSON virus_count (1993) differs from the number of nodes in the tree (2131)`
	* `ERROR:  The tree defined AA mutations on gene HA1 which doesn't appear in the metadata annotations object`

### Additions / fixes within the scope of this PR
* ~I’m not sure if the jsonschema install is correctly specified in `setup.py`. I’m trying to replicate `pip install git+git://github.com/Julian/jsonschema@9632422aa90cb1fbfbbb141954ef6d06437b0801`~ fixed below
* We may want to remove the “recommended” meta schema and make this the default instead.
* The schemas may need changing to support currently produced values (see errors / warnings above)
* The difference between the minimal & recommended metadata scheme. Currently, the recommended scheme extends the minimal scheme to raise warnings if fields are not defined in the minimal schema or if any of these fields are missing: `["title", "updated", "virus_count", "author_info", "annotations", "maintainer", "color_options", "panels"]`

### Extensions beyond this PR
* I’m going to work on stripping many of the deprecated exported key-value pairs fields `augur export`. This may require an additional `—nextflu-compatable` flag to `export` if some of these fields are required for nextflu.
* I’m going to propose schema alterations which we can comment on.
* Add version to metadata JSON
* Auspice should read the version & proceed accordingly

### CODE REVIEW

**Comment by trvrb** [comment]
@jameshadfield ---

This is a really great direction. One thing: I'm pretty sure you need to load `augur/data/schema_meta.json` differently than you do here: https://github.com/nextstrain/augur/blob/8dcb8c31b16bbd95a3ced7356a241b2789eae55e/augur/validate.py#L20

@tsibley pointed this out to me when I was loading tsvs in `augur/data/`. You should use `resource_stream` instead: https://github.com/nextstrain/augur/pull/136/commits/4017dcd04775fadf896f07f591880c5c077bb389

> It is strongly recommended that, if you are using data files, you should use the ResourceManager API of pkg_resources to access them.

More here: https://setuptools.readthedocs.io/en/latest/setuptools.html#accessing-data-files-at-runtime

**Comment by jameshadfield** [comment]
re: loading the files, the schema files, which are located in `augur/data` are loaded using `pkg_resources ` [at this line](https://github.com/nextstrain/augur/blob/8dcb8c31b16bbd95a3ced7356a241b2789eae55e/augur/validate.py#L60). The line you refer to is the command-line-argument JSONs.

**Comment by trvrb** [comment]
Ah. I see now. My mistake. Thanks @jameshadfield.

**Comment by trvrb** [comment]
After running `pip3 install --process-dependency-links .` and then running `augur validate --json auspice/zika_meta.json` I get the error:
```
module 'jsonschema' has no attribute 'Draft6Validator'
```
Makes me think the install is not working.

**Comment by jameshadfield** [comment]
Yup, I thought this may happen (see "Additions / fixes within the scope of this PR"). You can install it via `pip install git+git://github.com/Julian/jsonschema@9632422aa90cb1fbfbbb141954ef6d06437b0801`. Clearly the `install.py` needs to be fixed.

**Comment by trvrb** [comment]
48e1ea6707dce07cb31574b73950c1d8f0dfb955 fixes this issue. `augur validate` works for me in fresh Virtualenv now.

**Comment by trvrb** [comment]
@jameshadfield --- Okay, with this installed, it's working really well. I ran it against a number of existing JSONs and the resulting errors and warnings were mostly interpretable. There were some things like running `augur validate --json zika_meta.json` on live Zika meta:
```
ERROR: 'https_//www.ncbi.nlm.nih.gov/pubmed/28538727' is not valid under any of the given schemas. Trace: ... - patternProperties - ^.+$ - properties - paper_url - oneOf
```
Where I can see this was from `https_`, but wouldn't get this from the error message. Okay to revise these outside the scope of this PR.

**Pull request merged**
