### PR TITLE
Improved handling of JSONs from mismatched augur versions

### LINKED ISSUE #395: Indentation of exported JSONs
Currently, the indentation of (most) JSONs written by augur uses an indentation level of 1, or None if `AUGUR_MINIFY_JSON` is set -- see https://github.com/nextstrain/augur/blame/master/augur/utils.py#L199.

The current implementation of augur export (augur versions v5 + v6) use a different approach, obeying the `--minify-json` argument _not_ the env variable, and using an indentation of 2 if this is not set -- see https://github.com/nextstrain/augur/blame/master/augur/export.py#L469. 

@huddlej what's best to do here? should we minify jsons if _either_ the env variable or the argument is set? 

Perhaps separately I also prefer default indentation levels of 2, @tsibley did you choose 1  for a particular reason?

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR accomplishes 5 tasks:

## Writes the augur version when producing JSONs
All calls to `write_json` will now write a JSON containing the augur version under the `augur_version` key, in an opt-out fashion. The `augur export` calls do not  write out the augur version (although they probably could, as it's not the key that auspice looks for). 

## Enforce augur (major) version matches, if present
`read_node_data` will now die with a helpful error message if a provided JSON specifies an augur version which has a different major-version-number than the currently running augur. If an augur version is not specified no checks are run. This allows non-augur-produced JSONs to be used without requiring a version number (good), but also allows augur-v5 JSONs to be used in augur-v6  (potentially bad).

## Improves JSON indentation
Previously, the env variable `AUGUR_MINIFY_JSON` was not being respected by `augur export`. Minified JSONs can now be produced by `augur export` via the env variable or the command line flag `--minify-json`. We now have a default JSON indentation of 2 spaces for all JSONs written by augur (previously it was 2 for `augur export` and 1 for all other subcommands). Closes #395.

## Validate JSON produced by `augur translate`
Any JSON which contains an `annotations` block will have that validated against a JSON schema. 
This particular section of node-data JSON was chosen as it has changed between augur v5 & v6, and this PR will print a message and exit if such a JSON is loaded from an augur-v6 command. 

## Other improvements 
This PR improves error handling inside `read_node_data`, favoring a "exit-and-provide-a-helpful-message" approach. See comments in code for further details.

### CODE REVIEW

**Comment by rneher** [comment]
thanks James. This looks good! I have one thought though: What if a thirdparty script/tool produces a JSON. It would be good to have a `generated-by =('my_favorite_tool', 'v0.9.12')` in those jsons. We of course have no control on whether those are compatible with down-stream steps... @tsibley, do you know how such cases are handled?

**Comment by tsibley** [comment]
There is conversation happening in [#nextstrain-compute](https://bedfordlab.slack.com/archives/C131TERB5/p1573092904042100) that has impact on this PR, so would be good to resolve those discussions and come a decision before merging this.

**Comment by tsibley** [comment]
@rneher I would make the generator/producer metadata explicit, something like:

```json
{
  "generated_by": {
    "program": "my favorite tool",
    "version": "0.9.12",
    …
  }
}
```

This leaves generator metadata extensible by other keys, which might include commonly-desired information like additional version details or the actual command-line invocation used.

**Comment by jameshadfield** [comment]
Thanks for the input (both here & on slack) 👍

**Comment by trvrb** [comment]
Nice. Thank you James!

**Comment by emmahodcroft** [comment]
Thank you James! Sorry I didn't comment earlier, but how it ended up all looks good to me.

**Pull request merged**
