### PR TITLE
Validate

### PR DESCRIPTION
**Pull request by jameshadfield**
This rewrites the `augur validate` interface & turns it into a much more useful prospect that I see playing a big role throughout augur.

## As a augur command
Currently these commands work, but more will come (maybe pre v6 release, maybe not)
```
augur validate export-v2 <JSON>
augur validate export-v1 <META_JSON> <TREE_JSON>
augur validate auspice-config-v2 <JSON>
```
And exits with non-zero code if there are errors. (There are far fewer warnings printed out than previously, but still work to be done here). 

## As an import into other augur commands
I see this being used in various different commands for various files -- e.g. validate node-data JSONs, auspic config JSON etc etc.

Currently i've only implemented this for `augur export v2` to validate the for-auspice JSON:
```
from .validate import export_v2 as validate_v2
from .validate import ValidateError
try:
    validate_v2(json_v2=args.output_main)
except ValidateError as e:
    # handle as you wish
```

## schema -> HTML
@eharkins showed my a nice trick where you can turn your JSON schemas into human-readable HTML pages (i.e. part of the docs). This would be something to pursue for us. 

@rneher @trvrb @emmahodcroft are you happy with the look of this?

### CODE REVIEW

**Comment by emmahodcroft** [comment]
From this merge I am now getting validate errors that I don't think should be popping up. I'll create a branch to try and fix them - but if we are going to include this by default in `export v2` I think we need to super-test this on all kinds of datasets, as I think these 'errors' will make people think it has not exported (at least in my case it has, and works fine).

**Comment by tsibley** [comment]
++  for making validation be runnable as a simple function. One thing I've never been clear on is why validation isn't automatically run by `augur export`. It seems really weird to allow (or even expect?) `augur export` to occassionally produce invalid output but not tell you about it.

(Validation commands for the Auspice config file make more sense, as that is often hand-written.)

**Comment by jameshadfield** [comment]
> One thing I've never been clear on is why validation isn't automatically run by augur export.

That's what this PR does.

**Comment by trvrb** [comment]
>That's what this PR does.

This was a nice feature when upgrading `nextstrain/zika` to `augur export v2`.

**Comment by tsibley** [comment]
> That's what this PR does.

Oh! Awesome. I misinterpreted "Currently i've only implemented this for `augur export v2` to validate the for-auspice JSON". :+1:

**Pull request merged**
