### PR TITLE
io: Parse metadata with C engine, restrict to either CSV or TSV

### PR DESCRIPTION
**Pull request by victorlin**
### Description of proposed changes

See commit messages.

### Related issue(s)

Thinking about this since I'm making similar changes for the augur filter database implementation.

### Testing

- [x] Test added
- [x] Checks pass

### Checklist

- [x] Add a message in [CHANGES.md](https://github.com/nextstrain/augur/blob/HEAD/CHANGES.md) summarizing the changes in this PR that are end user focused. Keep headers and formatting consistent with the rest of the file.

### CODE REVIEW

**Comment by fanninpm** [comment]
You could also use [`csv.Sniffer.sniff()`](https://docs.python.org/3/library/csv.html#csv.Sniffer.sniff) to return a `Dialect`, which can be passed in to `pandas.read_csv()` as the `dialect` keyword argument.

**Comment by tsibley** [comment]
> The only concern would be if anyone is leveraging the Python parser for a non-tab-delimited file (e.g. `metadata.csv`). This would be a breaking change.

I'm not sure if this is an acceptable trade off. Diving into history, Augur's supported CSV for metadata [since at least 2018](https://github.com/nextstrain/augur/commit/6dac7eb927cf5fe2454d5dd00b94de98a82f5b7a#diff-8f66173c8ddc9d2afae3a0146d3abfcf6004537354e5ba7cec8fdf5186c3c0f0R6) and delimiter sniffing [since mid-2020](https://github.com/nextstrain/augur/commit/e8febc6a62a569dd6ab59c91fc72ad5983899c7a#diff-3561f9cb9bf4b6b0042881a7aa6024465e20d0bb241aa887c0fbb3bb7b4181daR93-R94).

@huddlej may have thoughts here too.

**Comment by huddlej** [comment]
I agree, @tsibley, that we can't drop CSV support. The original context for the current implementation is described in https://github.com/nextstrain/augur/issues/574. There are two separate problems:

1. determining the delimiter of an input file
2. efficiently parsing a file given its delimiter

In the older Augur implementations, we addressed problem 1 by inspecting the extension of the input filename. This led to the problems in #574. We opted for the convenience of [pandas's delimiter sniffer in Python parser mode](https://github.com/pandas-dev/pandas/blob/f2e707b4ca69c9515a555b960cff8dfd8c0c0a70/pandas/io/parsers/python_parser.py#L208), to solve this problem at the expense of a slower solution to problem 2.

As @fanninpm points out, we could use `csv.Sniffer` directly on the first line of the input file in `read_metadata`. Once we know the delimiter, we could call `read_csv` with that delimiter and use the C engine to parse. This would solve both problems without breaking backward compatibility.

**Comment by victorlin** [comment]
Thanks @fanninpm @tsibley @huddlej for the comments and suggestions. I finally updated this PR to use `csv.Sniffer`.

**Review by joverlee521 — APPROVED** [review]
LGTM!

**Comment by victorlin** [comment]
@joverlee521 I pushed a couple touch-ups (70d8150058a1cddff64ade7e0c65caa40e9d800e...2783ef848364eead14dd91d431753a5f0e5fb502), do those LGTY?

**Comment by joverlee521** [comment]
@victorlin Changes look good! (Ignoring the unrelated failing Cram test)

**Pull request merged**
