### PR TITLE
deletion extension seems messed up, this should fix it

### PR DESCRIPTION
**Pull request by rneher**

### CODE REVIEW

**Comment by rneher** [comment]
hadn't realized that they weren't sorted properly. they need to be ordered by position of course (I didn't test it as I was on the road running on battery...).  Could you commit this once tested?

**Comment by huddlej** [comment]
Done! This should be ready to merge.

**Comment by rneher** [comment]
thanks, John.

**Comment by trvrb** [comment]
Thanks both!

**Pull request merged**
