### PR TITLE
Combined merge

### PR DESCRIPTION
**Pull request by trvrb**
Merge latest work into `master`. This includes @rneher's work on seasonal flu, @jameshadfield's work on H7N9, @sidneymbell's work on dengue and my recent work on Zika. I think I got all the merges correctly done, but some things may have slipped through. Would be good to test.

### CODE REVIEW

**Comment by sidneymbell** [comment]
Dengue is working. Thanks, Trevor!

**Comment by trvrb** [comment]
* Zika working
* Ebola working
* H7N9 is failing. Working on this now.

**Comment by trvrb** [comment]
Thanks for catching this @rneher. Was unintentional reversion. I'll restore.

**Comment by trvrb** [comment]
I think this is resolved now. @rneher: What had happened was that `root_state` was implemented on `master` and `missing` was implemented on `H7N9`. Appears to work now. And H7N9 is working as well. I'll do a bit more testing, but I think this is ready to merge.

**Comment by trvrb** [comment]
- [ ] Zika rebuild
- [ ] Ebola rebuild
- [ ] H7N9 rebuild
- [ ] Dengue rebuild

**Comment by trvrb** [comment]
Tracking down error in H7N9. It comes from RAxML building. Looking at standard out shows:

```
RAxML was called as follows:

raxml -f e -T 2 -s temp.phyx -n branches -c 25 -m GTRGAMMA -p 344312987 -t raxml_tree.newick 


RAxML expects to read a taxon label in the tree file
but the taxon label is an empty string.

RAxML will print the context of the error and then exit:

/1051:0.00060,(((((:0.00055,(A/GD-103/20
```

I'll figure out why the taxon label (strain name) is missing.

**Comment by trvrb** [comment]
I'm still getting this error from running RAxML on the full H7N9 dataset. However, I think it's best if we finally get this merged and I'll make a separate issue for the H7N9 build.

**Pull request merged**
