### PR TITLE
Seasonal flu mods

### PR DESCRIPTION
**Pull request by trvrb**
This branch includes @rneher's work on seasonal flu requiring new or significantly updated augur functions for `frequencies`, `reconstruct-sequences` and `titers`. However, there is are almost no code changes outside of these functions.

This is passing tests on Travis CI and other builds appear to still work.

We may want to hash out exactly how `reconstruct-sequences` should work in terms of interface however.

### CODE REVIEW

**Comment by rneher** [comment]
I changed `reconstruct_sequences.py` to operate on single genes. Haven't tested the vcf part yet.

**Comment by emmahodcroft** [comment]
Yes - seems to work with VCF

**Comment by tsibley** [comment]
Seems reasonable to merge to master sooner than later, as it is the line of current development.

**Comment by huddlej** [comment]
I'm OK with having this merged to master now, if others are OK with the recent LBI/distance subcommands. Tip frequencies still need to be added for the seasonal flu build, but that could be a separate smaller PR.

**Pull request merged**
