### PR TITLE
Declare dependencies with version ranges rather than single versions

### PR DESCRIPTION
**Pull request by tsibley**
…and lock exact versions in a simple, hopefully obvious
requirements-locked.txt file.  Notably, the exact versions are locked
with `pip freeze` so that transitive deps are included as well.  This
helps install in more diverse environments and should require less
manual co-ordination between sacra and augur.  It also more precisely
pins all dep versions when using the lock file.

I generated the requirements-locked.txt using `pip freeze --local` in a
clean virtualenv after installing the updated requirements.txt.  The
version ranges were determined after manually checking the versioning
policies or practices of our deps.

The general idea here is based on "A Better Pip Workflow".¹  While
Pipenv now exists for this problem space, it's an additional layer of
tooling that we'd like to see if we can avoid for now.

¹ https://www.kennethreitz.org/essays/a-better-pip-workflow

### CODE REVIEW

**Comment by tsibley** [comment]
@rneher If you have a chance, I'd appreciate your eyes on these proposed changes.  I think they start moving dep management in a better direction, but your input guided by more time in Python would be useful.  This ultimately came out of [conversation around sacra's deps](https://github.com/nextstrain/sacra/pull/20).

(Also, hi!  I don't know that we've met, but as of last week I'm working in Trevor's group.)

**Comment by trvrb** [comment]
@tsibley --- I'm very happy with this direction.

**Comment by rneher** [comment]
Hi @tsibley, yes, this direction is generally useful. I am a little worried that many of these will change as we move to augurlinos. The old pipeline is py2, the new one py3, so this is generating all sorts of headaches until we have fully transitioned. Also, many should be optional. For example seaborn or the git stuff which depends on binaries. if import pygit throws an import error, we can skip this. 

To handle binaries such as raxml and mafft, conda environments might be useful.

**Comment by tsibley** [comment]
@rneher Nod. This isn't meant to be set in stone, just a better description of the current set of deps. I certainly expect it to change over time, particularly with a 2 → 3 transition.

Regarding optional deps, I don't think there's a good way to express those in requirements.txt.  It seems unnecessary to me to make deps optional unless they're onerous to satisfy.  GitPython nor seaborn, for example, meets that criteria.

In terms of handling the broader environment for raxml, mafft, and more, I agree that we should also pursue either conda environments or containers or something of that ilk.  I consider that a separate task—one with larger nextstrain implications than augur alone—and it's one I'll be pursuing.

Any objections to merging this as a tiny step?

**Comment by tsibley** [comment]
(I'm going to merge this.)

**Pull request merged**
