### PR TITLE
Add initial unit tests for the lbi.py module. Also add docstrings to …

### PR DESCRIPTION
**Pull request by lcwheeler**
…the lbi.py select_nodes_in_season

function. Tests require the data from the output of Zika tutorial Snakefile, which I have added in the
/tests/data/zika-tutorial directory.

### Description of proposed changes    
What is the goal of this pull request? What does this pull request change?

### Related issue(s)  

Fixes #  
Related to #  

### Testing
What steps should be taken to test the changes you've proposed?  
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?

### CODE REVIEW

**Comment by lcwheeler** [comment]
Linked with issue #476 https://github.com/nextstrain/augur/issues/476

**Comment by Zsailer** [comment]
@lcwheeler, it looks like the example zika data you're using in your tests are listed as a "git submodule". This submodule is never initialized in the tests, so the tests can't find the data you're calling. 

First, I would avoid using git submodules for tests. Let's add source files here instead to make the test setup easy. Second, we suggest we open a separate PR that adds test data as pytest fixtures. Then, your PR and my PR (#504) can depend on those fixtures. How does that sound?

**Comment by lcwheeler** [comment]
@Zsailer Sounds good. I think the reason the data ended up being a submodule is that I cloned this repo https://github.com/nextstrain/zika-tutorial.git, ran the Snakemake tutorial, and then copied the directory into tests/data. Adding the test data as fixtures instead sounds like a good idea.

**Comment by huddlej** [comment]
Closing this as part of routine PR/issue clean-up.

**Pull request closed without merging**
