### PR TITLE
Add support for FASTA output to ancestral subcommand

### LINKED ISSUE #292: augur ancestral should support FASTA output
As @emmahodcroft noted internally back in May, it is strange that `augur ancestral` does not provide a way to export the ancestral sequences to FASTA in addition to (or instead of) the current JSON output.

Emma's original use case was tracing a translation issue from the original nucleotide sequences. Another use case is applying the `augur distance` command to nucleotide sequences where the root sequence needs to be available for distance comparisons.

I would like to propose the addition of two new options for the `augur ancestral` command:

  - `--output-fasta` to allow specification of a FASTA output file
  - `--output-json` to match the FASTA output flag and provide an unambiguous option that we keep as redundant with the existing `--output` option for backwards compatibility

Users should be able to specify one or both of these flags to match their use case.

I also propose we phase out the current `--output` flag with the next major version release and print a deprecation warning until then.

### PR DESCRIPTION
**Pull request by huddlej**
Adds a new flag `--output-fasta` and logic to support saving ancestral sequences
and leaves from the given tree to a FASTA file. Also adds a redundant, more
specific flag `--output-json` that will replace the current `--output` flag in
the next major version release of augur. For now, we issue a deprecation warning
when the `--output` flag is used.

Closes #292.

### CODE REVIEW

**Comment by trvrb** [comment]
@huddlej ---

Thanks for putting this in. One thought:

We do have a couple instances of modules with multiple `--output-` flags like `augur refine` with `--output-tree` and `--output-node-data`. In most these cases both files are required outputs. Although another big example is `augur export` where we have `--output-main`, `--output-tree`, `--output-sequence` and `--output-meta` where different combinations may be used. This analogy is perhaps helpful in that I think I'd like `--output-main` to be used here even if that's the only output flag (rather than the alternative of making main be just `--output`). So the pattern becomes "any module that allows multiple output files must append a file type to each output command". In this case, I'd be in favor of proceeding with deprecating `--output` for `augur ancestral`.

I would note that this bit of `augur ancestral`, `augur translate` and `augur reconstruct-sequences` seems ripe for refactor. I don't necessarily have a better suggestion for data flow however.

**Comment by tsibley** [comment]
I agree on qualifying `--output` with a suffix, but `--output-main` seems unnecessarily vague to me as it doesn't indicate what "main" is. For this command, the more specific `--output-json` that John chose seems more descriptive.

(I think `--output-main` makes sense for `augur export` because it parallels `foo_main.json`, `foo_tree.json`, etc.)

**Comment by huddlej** [comment]
It looks like our general pattern is to specify the contents of the file rather than the format of the output. So, `--output-fasta` would be more consistent as `--output-sequences` and `--output-json` would be more consistent as `--output-node-data`.

**Comment by trvrb** [comment]
This is a good point. I think I would prefer `--output-sequences` and `--output-node-data`.

**Comment by huddlej** [comment]
Thanks @emmahodcroft ! I just pushed some changes to disable sequence output for VCF inputs. I confirmed these changes work with the Zika and TB builds.

If everything else is otherwise good, I will rebase this into one commit and merge.

**Comment by trvrb** [comment]
Nice! Looks good to me.

**Pull request merged**
