### PR TITLE
Root sequence

### PR DESCRIPTION
**Pull request by rneher**
this exports the root or reference sequence into a separate json. So far only v1. The vcf case relies on `translations_reference.fasta` and I couldn't find where this is generated (@emmahodcroft , please amend as necessary).

### CODE REVIEW

**Comment by emmahodcroft** [comment]
V1 TB seems to work and validate
V1 Zika just needed a key name fix and it works and validates
(note the '_seq' file isn't validated for either of these!)

V2 Zika now has `sequence` and `aa_sequences` within the JSON- I moved `aa_sequences` out of being a trait and made both sit at the level of `accession` and `authors` in the schema.json. I'm not sure if this is ideal, or if they should be put within some other container. This now validates. 
(@jameshadfield would be good for you to look this and over my patterns/descriptions etc)

For V2 TB, I assume we don't want these to go into one JSON...? (As it'll increase the size substantially.) If not, we could do what's done in V1 so it's written out as _seq.json even in V2.

**Comment by jameshadfield** [comment]
Thanks for this work @emmahodcroft and @rneher (especially modifying the schema to pass!). I'm fully on board with the aim, but there's a few points which I think bear thinking about. 

1. I thought we wanted to put root node sequences as a separate, top-level property (i.e. the meta file has top level properties `tree`, `meta` and `sequences`). It looks to me as if you've added these to the root node (not being traits there is fine). @trvrb and @huddlej would be the best people to weigh in on this.

2. It seems a little strange to group `nuc` & `aa` muts into a single `mutations` property (which I like), but have `sequences` and `aa_sequences` separate.

3. re: "V2 TB, I assume we don't want these to go into one JSON...?". One option which we've thought about is to have these as properties in the main json, which could be the data structure if small enough, or a string pointing to the file which contains this (larger) data. If so, then frequencies(and future "extra" files) would parallel this.

**Comment by emmahodcroft** [comment]
1 & 2. I'd agree on both
3. We discussed this two weeks ago and I forgot! Sorry 🙃

**Comment by tsibley** [comment]
> One option which we've thought about is to have these as properties in the main json, which could be the data structure if small enough, or a string pointing to the file which contains this (larger) data.

Worth thinking about is that if the normal value is also a string, then it can become ambiguous if the value is a filename or not.

**Comment by emmahodcroft** [comment]
I went ahead and grouped both (now `nuc_sequence` and `aa_sequences`) into `sequences` and moved to top-level.

**Comment by rneher** [comment]
merging this now. it outputs a pretty simple json with nucleotide sequence and translations if an output file is specified. otherwise doesn't change behavior.

**Pull request merged**
