### PR TITLE
Move AugurError to new errors.py, replace RuntimeError

### PR DESCRIPTION
**Pull request by victorlin**
### Description of proposed changes

See commit messages.

### Related issue(s)

Suggested by @tsibley: https://github.com/nextstrain/augur/pull/918#pullrequestreview-970072170

### Testing

Tests modified accordingly.

### CODE REVIEW

**Comment by victorlin** [comment]
Cyclic dependency between `augur.utils` and `augur.util_support`...

**Review by huddlej — CHANGES_REQUESTED** [review]
Thanks, @victorlin! What if we placed `AugurError` in a new `errors.py` or `exceptions.py` top-level module in `augur` ([sort of like pandas does](https://github.com/pandas-dev/pandas/blob/main/pandas/errors/__init__.py), only simpler)? This organization should address this and future circular import issues. I also prefer `from .errors import AugurError` over `from .utils import AugurError` for readability.

**Comment by victorlin** [comment]
@huddlej good suggestion, done: 2af104509c26bc0cca3d1d0d77961d05b2c476f5

**Comment by huddlej** [comment]
@victorlin I'd probably drop that change for now. Seeing all of those imports at the top should be a good reminder for us to move the util support logic back into utils at some point... :)

**Review by tsibley — APPROVED** [review]

**Pull request merged**
