### PR TITLE
Remove Snakemake tests (and dependency)

### LINKED ISSUE #753: Remove Snakemake as a dependency
**Context**  

Snakemake is not required to use Augur, but we still use it for some functional tests in Travis CI. These tests can be easily run with cram and this additional dependency of Snakemake adds unnecessary complexity to the project. It also causes recent versions of Snakemake from a Conda installation to get overwritten by an older, pip-installed, and less complete version of Snakemake which complicates the dev environment.

**Description**   
Replace Snakemake tests in CI with cram tests and remove Snakemake as a dev dependency.

### PR DESCRIPTION
**Pull request by victorlin**
## Description of proposed changes

Main motivation is to remove Snakemake from the list of dev dependencies. This will likely cause a drop in test coverage, which can be seen by the codecov coverage report (as a comment on this PR once CI finishes running). However, note that pathogen-repo-ci is not currently factored into those coverage reports.

## Related issue(s)

- Closes #753

## Checklist

- [x] Checks pass
- ~[ ] If making user-facing changes, add a message in [CHANGES.md](https://github.com/nextstrain/augur/blob/HEAD/CHANGES.md) summarizing the changes in this PR~

### CODE REVIEW

**Review by jameshadfield — APPROVED** [review]
I'm not concerned about the TB build here being out-of-date cf. the TB repo, the latter should be the correct point of reference.

**Comment by victorlin** [comment]
@codecov comment above does not tell the full story. No coverable lines were changed directly, but [there are definitely coverage drops](https://app.codecov.io/gh/nextstrain/augur/pull/1302/indirect-changes)...

**Comment by jameshadfield** [comment]
> I'll have to take a deeper look. Thoughts from anyone?

@victorlin I wouldn't let the numbers codecov reports stop this from being merged - remember it's supposed to be a tool to help us, not prevent progress. The PR looks sound to me.

**Comment by victorlin** [comment]
Thanks @jameshadfield, I'll merge this now!

**Pull request merged**
