### PR TITLE
Begin work on augur modules

### PR DESCRIPTION
**Pull request by trvrb**
This PR contains @rneher's initial classes to implement `augur align` and `augur tree` modules. `align.py` should be a good template for creating additional modules. A couple things to note:

1. Parser for `align.py` is contained in `bin/augur`. Command line interface is thus through calling `augur align` which is shorthand for `python bin/augur align`. It won't work to call `python augur/align.py`. This puts the entire command line interface in one place, which seems good.

2. `align.py` contains a method called `run` which is it's entrypoint. Each module should have a `run` method.

@huddlej: Could you take a look at this and see if you're happy with this as a template?

### CODE REVIEW

**Comment by trvrb** [comment]
Ignore the failed checks. I had Travis CI configured wrong. Changed it to just work on `nextstrain.org` repo.

**Comment by trvrb** [comment]
>It is confusing that the logic/code for the traits subcommand is in a module named mugration. This should be consistently named one thing (I don’t care which).

I would rename this module to `traits.py`. All modules should have the same name as their interface.

>Should intermediate files be written to a temporary directory like the current augur process commands do? Snakemake has the ability to run any rule in a “shadow directory” such that all files for the rule are created in a temporary directory and cleaned up automatically after the rule completes. This would let build maintainers choose what happens to intermediate files.

I would favor allowing users to explicitly specify input and output files. Wrapping in Snakemake would allow making these temp directories. If there are intermediates created when running a module (like intermediate RAxML files) I would create a temp directory and delete at end of call.

>Instead of copying code from base into the respective subcommand modules, we should just import the original code from base initially. This prevents forking code within a repository and it will be easy later to move the files we need from base into augur and delete anything that didn’t get used.

I agree, at least to a large degree. I think it will be cleaner to just rewrite `tree.py` and `traits.py`. There is very little internal logic to these. I would import `frequencies` and `titers`.

>It would be nice to have a flag for align to prevent trimming of non-reference bases after alignment (I think this used to exist and was removed from the current prototype).

Agree. This is in the GDoc spec.

---------------------

Generally, I think the most conducive way to further discussion here will be to merge this PR. And make separate PRs / discussions of individual modules. Too much going on here...

**Comment by rneher** [comment]
My take on the many arguments of the tree builders and aligners is that we provide reasonable defaults that work for most viruses. If users know what they are doing, they can always provide a newick as input and skip the tree building part. But a command `augur tree` that takes an alignment + metadata and spits out a timetree + ancestral reconstruction is a useful bundle of features. otherwise agree with everything said above...

**Comment by trvrb** [comment]
I'm going to merge this now as it's getting a bit unwieldy. Would be good to do branches for specific modules. I think should help frame PRs. Thanks for the work on this @emmahodcroft, @huddlej and @rneher.

**Pull request merged**
